#ifndef DIO_CFG_H
#define DIO_CFG_H

/** \brief AUTOSAR Dio DIO Driver
 **
 ** This file contains target independent configuration declarations for the
 ** AUTOSAR module Dio.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL40-DRV
 **
 ** (c) 2014-2017, Cypress Semiconductor Corporation. All rights reserved.
 **
 ** Warranty and Disclaimer
 **
 ** This software product is property of Cypress Semiconductor Corporation or
 ** its subsidiaries.
 ** Any use and/or distribution rights for this software product are provided
 ** only under the Cypress Software License Agreement.
 ** Any use and/or distribution of this software product not in accordance with
 ** the terms of the Cypress Software License Agreement are unauthorized and
 ** shall constitute an infringement of Cypress intellectual property rights.
*/
/*==================[includes]===============================================*/
#include <ErrorCalloutHandler.h>

/*==================[macros]=================================================*/

#define DIO_GEN_MODULE_ID           120U
#define DIO_GEN_VENDOR_ID           66U
#define DIO_GEN_AR_RELEASE_MAJOR_VERSION    4U
#define DIO_GEN_AR_RELEASE_MINOR_VERSION    0U
#define DIO_GEN_AR_RELEASE_REVISION_VERSION    3U
#define DIO_GEN_SW_MAJOR_VERSION    1U
#define DIO_GEN_SW_MINOR_VERSION    0U
#define DIO_GEN_SW_PATCH_VERSION    27U


#define DIO_GET_VERSION_INFO_API STD_ON

#define DIO_FLIP_CHANNEL_API STD_ON

#define DIO_DEV_ERROR_DETECT STD_ON


/*------------------[DIO Driver Port array index      ]----------------------*/
/** \brief derivate specific number of ports */
#define DIO_NUMBER_OF_PORTS   7U

/*------------------[DIO Driver Symbolic Port Names    ]---------------------*/
#if (defined DioConf_DioPort_DIO0)
#error "DioConf_DioPort_DIO0 already defined"
#endif
#define DioConf_DioPort_DIO0  0U
#if (defined DioConf_DioPort_DIO2)
#error "DioConf_DioPort_DIO2 already defined"
#endif
#define DioConf_DioPort_DIO2  2U
#if (defined DioConf_DioPort_DIO3)
#error "DioConf_DioPort_DIO3 already defined"
#endif
#define DioConf_DioPort_DIO3  3U
#if (defined DioConf_DioPort_DIO4)
#error "DioConf_DioPort_DIO4 already defined"
#endif
#define DioConf_DioPort_DIO4  4U
#if (defined DioConf_DioPort_DIO5)
#error "DioConf_DioPort_DIO5 already defined"
#endif
#define DioConf_DioPort_DIO5  5U
#if (defined DioConf_DioPort_DIO6)
#error "DioConf_DioPort_DIO6 already defined"
#endif
#define DioConf_DioPort_DIO6  6U

/*------------------[DIO Driver Symbolic Channel Names ]---------------------*/
#if (defined DioConf_DioChannel_DIO_UNUSED_P0_19)
#error "DioConf_DioChannel_DIO_UNUSED_P0_19 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P0_19 19U
#if (defined DioConf_DioChannel_DIO_UNUSED_P0_00)
#error "DioConf_DioChannel_DIO_UNUSED_P0_00 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P0_00 0U
#if (defined DioConf_DioChannel_DIO_UNUSED_P0_17)
#error "DioConf_DioChannel_DIO_UNUSED_P0_17 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P0_17 17U
#if (defined DioConf_DioChannel_DIO_UNUSED_P0_02)
#error "DioConf_DioChannel_DIO_UNUSED_P0_02 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P0_02 2U
#if (defined DioConf_DioChannel_DIO_UNUSED_P0_03)
#error "DioConf_DioChannel_DIO_UNUSED_P0_03 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P0_03 3U
#if (defined DioConf_DioChannel_DIO_TFT_RESET)
#error "DioConf_DioChannel_DIO_TFT_RESET already defined"
#endif
#define DioConf_DioChannel_DIO_TFT_RESET 16U
#if (defined DioConf_DioChannel_DIO_UNUSED_P0_11)
#error "DioConf_DioChannel_DIO_UNUSED_P0_11 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P0_11 11U
#if (defined DioConf_DioChannel_DIO_RESET_CON)
#error "DioConf_DioChannel_DIO_RESET_CON already defined"
#endif
#define DioConf_DioChannel_DIO_RESET_CON 26U
#if (defined DioConf_DioChannel_DIO_UNUSED_P0_31)
#error "DioConf_DioChannel_DIO_UNUSED_P0_31 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P0_31 31U
#if (defined DioConf_DioChannel_DIO_UNUSED_P0_01)
#error "DioConf_DioChannel_DIO_UNUSED_P0_01 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P0_01 1U
#if (defined DioConf_DioChannel_DIO_SHUT_DOWN)
#error "DioConf_DioChannel_DIO_SHUT_DOWN already defined"
#endif
#define DioConf_DioChannel_DIO_SHUT_DOWN 27U
#if (defined DioConf_DioChannel_DIO_UNUSED_P0_28)
#error "DioConf_DioChannel_DIO_UNUSED_P0_28 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P0_28 28U
#if (defined DioConf_DioChannel_DIO_UNUSED_P0_18)
#error "DioConf_DioChannel_DIO_UNUSED_P0_18 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P0_18 18U
#if (defined DioConf_DioChannel_DIO_UNUSED_P2_16)
#error "DioConf_DioChannel_DIO_UNUSED_P2_16 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P2_16 80U
#if (defined DioConf_DioChannel_DIO_UNUSED_P2_17)
#error "DioConf_DioChannel_DIO_UNUSED_P2_17 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P2_17 81U
#if (defined DioConf_DioChannel_DIO_P_3V3SW_EN)
#error "DioConf_DioChannel_DIO_P_3V3SW_EN already defined"
#endif
#define DioConf_DioChannel_DIO_P_3V3SW_EN 86U
#if (defined DioConf_DioChannel_MDI_Low_OilPressure_uC)
#error "DioConf_DioChannel_MDI_Low_OilPressure_uC already defined"
#endif
#define DioConf_DioChannel_MDI_Low_OilPressure_uC 83U
#if (defined DioConf_DioChannel_DIO_MDO_SHIFT_BAR_EN)
#error "DioConf_DioChannel_DIO_MDO_SHIFT_BAR_EN already defined"
#endif
#define DioConf_DioChannel_DIO_MDO_SHIFT_BAR_EN 91U
#if (defined DioConf_DioChannel_DIO_MDO_SHIFT_Telltale_EN)
#error "DioConf_DioChannel_DIO_MDO_SHIFT_Telltale_EN already defined"
#endif
#define DioConf_DioChannel_DIO_MDO_SHIFT_Telltale_EN 92U
#if (defined DioConf_DioChannel_DIO_MDI_IGN_INT)
#error "DioConf_DioChannel_DIO_MDI_IGN_INT already defined"
#endif
#define DioConf_DioChannel_DIO_MDI_IGN_INT 88U
#if (defined DioConf_DioChannel_DIO_MDO_FUEL_RED)
#error "DioConf_DioChannel_DIO_MDO_FUEL_RED already defined"
#endif
#define DioConf_DioChannel_DIO_MDO_FUEL_RED 95U
#if (defined DioConf_DioChannel_DIO_MDI_Passenger_SeatBelt)
#error "DioConf_DioChannel_DIO_MDI_Passenger_SeatBelt already defined"
#endif
#define DioConf_DioChannel_DIO_MDI_Passenger_SeatBelt 109U
#if (defined DioConf_DioChannel_DIO_B_CAN_MCU_STB)
#error "DioConf_DioChannel_DIO_B_CAN_MCU_STB already defined"
#endif
#define DioConf_DioChannel_DIO_B_CAN_MCU_STB 99U
#if (defined DioConf_DioChannel_DIO_B_CAN_MCU_RXD)
#error "DioConf_DioChannel_DIO_B_CAN_MCU_RXD already defined"
#endif
#define DioConf_DioChannel_DIO_B_CAN_MCU_RXD 101U
#if (defined DioConf_DioChannel_DIO_MDI_ParkBrake_Uc)
#error "DioConf_DioChannel_DIO_MDI_ParkBrake_Uc already defined"
#endif
#define DioConf_DioChannel_DIO_MDI_ParkBrake_Uc 107U
#if (defined DioConf_DioChannel_MDI_Low_Air_Pressure_uC)
#error "DioConf_DioChannel_MDI_Low_Air_Pressure_uC already defined"
#endif
#define DioConf_DioChannel_MDI_Low_Air_Pressure_uC 106U
#if (defined DioConf_DioChannel_DIO_MDI_AIRBAG_uC)
#error "DioConf_DioChannel_DIO_MDI_AIRBAG_uC already defined"
#endif
#define DioConf_DioChannel_DIO_MDI_AIRBAG_uC 110U
#if (defined DioConf_DioChannel_DIO_MDI_4W_L)
#error "DioConf_DioChannel_DIO_MDI_4W_L already defined"
#endif
#define DioConf_DioChannel_DIO_MDI_4W_L 104U
#if (defined DioConf_DioChannel_DIO_UNUSED_P3_07)
#error "DioConf_DioChannel_DIO_UNUSED_P3_07 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P3_07 103U
#if (defined DioConf_DioChannel_DIO_B_CAN_MCU_TXD)
#error "DioConf_DioChannel_DIO_B_CAN_MCU_TXD already defined"
#endif
#define DioConf_DioChannel_DIO_B_CAN_MCU_TXD 102U
#if (defined DioConf_DioChannel_DIO_DO_TCU_D_Uc)
#error "DioConf_DioChannel_DIO_DO_TCU_D_Uc already defined"
#endif
#define DioConf_DioChannel_DIO_DO_TCU_D_Uc 126U
#if (defined DioConf_DioChannel_DIO_UNUSED_P3_31)
#error "DioConf_DioChannel_DIO_UNUSED_P3_31 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P3_31 127U
#if (defined DioConf_DioChannel_DIO_P_CAN_MCU_RXD)
#error "DioConf_DioChannel_DIO_P_CAN_MCU_RXD already defined"
#endif
#define DioConf_DioChannel_DIO_P_CAN_MCU_RXD 112U
#if (defined DioConf_DioChannel_DIO_P_CAN_MCU_TXD)
#error "DioConf_DioChannel_DIO_P_CAN_MCU_TXD already defined"
#endif
#define DioConf_DioChannel_DIO_P_CAN_MCU_TXD 113U
#if (defined DioConf_DioChannel_DIO_MDI_Driver_SeatBelt)
#error "DioConf_DioChannel_DIO_MDI_Driver_SeatBelt already defined"
#endif
#define DioConf_DioChannel_DIO_MDI_Driver_SeatBelt 108U
#if (defined DioConf_DioChannel_DIO_P_CAN_MCU_STB)
#error "DioConf_DioChannel_DIO_P_CAN_MCU_STB already defined"
#endif
#define DioConf_DioChannel_DIO_P_CAN_MCU_STB 111U
#if (defined DioConf_DioChannel_DIO_Unused_P3_22)
#error "DioConf_DioChannel_DIO_Unused_P3_22 already defined"
#endif
#define DioConf_DioChannel_DIO_Unused_P3_22 118U
#if (defined DioConf_DioChannel_DIO_DO_TCU_S_uC)
#error "DioConf_DioChannel_DIO_DO_TCU_S_uC already defined"
#endif
#define DioConf_DioChannel_DIO_DO_TCU_S_uC 120U
#if (defined DioConf_DioChannel_DIO_DO_TCU_N_Uc)
#error "DioConf_DioChannel_DIO_DO_TCU_N_Uc already defined"
#endif
#define DioConf_DioChannel_DIO_DO_TCU_N_Uc 121U
#if (defined DioConf_DioChannel_MDI_LOCK_uC)
#error "DioConf_DioChannel_MDI_LOCK_uC already defined"
#endif
#define DioConf_DioChannel_MDI_LOCK_uC 125U
#if (defined DioConf_DioChannel_DIO_UNUSED_P4_02)
#error "DioConf_DioChannel_DIO_UNUSED_P4_02 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P4_02 130U
#if (defined DioConf_DioChannel_DIO_UNUSED_P4_25)
#error "DioConf_DioChannel_DIO_UNUSED_P4_25 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P4_25 153U
#if (defined DioConf_DioChannel_DIO_DSP_STANDBY_MODE)
#error "DioConf_DioChannel_DIO_DSP_STANDBY_MODE already defined"
#endif
#define DioConf_DioChannel_DIO_DSP_STANDBY_MODE 154U
#if (defined DioConf_DioChannel_DIO_UNUSED_P4_27)
#error "DioConf_DioChannel_DIO_UNUSED_P4_27 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P4_27 155U
#if (defined DioConf_DioChannel_DIO_UNUSED_P4_28)
#error "DioConf_DioChannel_DIO_UNUSED_P4_28 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P4_28 156U
#if (defined DioConf_DioChannel_DIO_MDO_P12V_EN)
#error "DioConf_DioChannel_DIO_MDO_P12V_EN already defined"
#endif
#define DioConf_DioChannel_DIO_MDO_P12V_EN 158U
#if (defined DioConf_DioChannel_DIO_DISP_PWR_EN)
#error "DioConf_DioChannel_DIO_DISP_PWR_EN already defined"
#endif
#define DioConf_DioChannel_DIO_DISP_PWR_EN 159U
#if (defined DioConf_DioChannel_DIO_UNUSED_P4_29)
#error "DioConf_DioChannel_DIO_UNUSED_P4_29 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P4_29 157U
#if (defined DioConf_DioChannel_DIO_UNUSED_P4_03)
#error "DioConf_DioChannel_DIO_UNUSED_P4_03 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P4_03 131U
#if (defined DioConf_DioChannel_DIO_UNUSED_P4_04)
#error "DioConf_DioChannel_DIO_UNUSED_P4_04 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P4_04 132U
#if (defined DioConf_DioChannel_MDIL_Exhaust_Brake_uC)
#error "DioConf_DioChannel_MDIL_Exhaust_Brake_uC already defined"
#endif
#define DioConf_DioChannel_MDIL_Exhaust_Brake_uC 135U
#if (defined DioConf_DioChannel_DIO_UNUSED_P4_08)
#error "DioConf_DioChannel_DIO_UNUSED_P4_08 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P4_08 136U
#if (defined DioConf_DioChannel_DIO_UNUSED_P4_09)
#error "DioConf_DioChannel_DIO_UNUSED_P4_09 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P4_09 137U
#if (defined DioConf_DioChannel_DIO_UNUSED_P4_10)
#error "DioConf_DioChannel_DIO_UNUSED_P4_10 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P4_10 138U
#if (defined DioConf_DioChannel_DIO_UNUSED_P4_11)
#error "DioConf_DioChannel_DIO_UNUSED_P4_11 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P4_11 139U
#if (defined DioConf_DioChannel_DIO_POWER_FAULT)
#error "DioConf_DioChannel_DIO_POWER_FAULT already defined"
#endif
#define DioConf_DioChannel_DIO_POWER_FAULT 140U
#if (defined DioConf_DioChannel_DIO_MDI_CHARGE_uC)
#error "DioConf_DioChannel_DIO_MDI_CHARGE_uC already defined"
#endif
#define DioConf_DioChannel_DIO_MDI_CHARGE_uC 128U
#if (defined DioConf_DioChannel_DIO_UNUSED_P4_01)
#error "DioConf_DioChannel_DIO_UNUSED_P4_01 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P4_01 129U
#if (defined DioConf_DioChannel_DIO_P_5VSW_EN)
#error "DioConf_DioChannel_DIO_P_5VSW_EN already defined"
#endif
#define DioConf_DioChannel_DIO_P_5VSW_EN 133U
#if (defined DioConf_DioChannel_DIO_MDO_SHIFT_RCK)
#error "DioConf_DioChannel_DIO_MDO_SHIFT_RCK already defined"
#endif
#define DioConf_DioChannel_DIO_MDO_SHIFT_RCK 134U
#if (defined DioConf_DioChannel_DIO_UNUSED_P5_06)
#error "DioConf_DioChannel_DIO_UNUSED_P5_06 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P5_06 166U
#if (defined DioConf_DioChannel_DIO_UNUSED_P5_07)
#error "DioConf_DioChannel_DIO_UNUSED_P5_07 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P5_07 167U
#if (defined DioConf_DioChannel_DIO_UNUSED_P5_20)
#error "DioConf_DioChannel_DIO_UNUSED_P5_20 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P5_20 180U
#if (defined DioConf_DioChannel_DIO_MDI_TFT_BL1_FAULT)
#error "DioConf_DioChannel_DIO_MDI_TFT_BL1_FAULT already defined"
#endif
#define DioConf_DioChannel_DIO_MDI_TFT_BL1_FAULT 161U
#if (defined DioConf_DioChannel_DIO_UNSUED_P5_27)
#error "DioConf_DioChannel_DIO_UNSUED_P5_27 already defined"
#endif
#define DioConf_DioChannel_DIO_UNSUED_P5_27 187U
#if (defined DioConf_DioChannel_DIO_UNUSED_P5_28)
#error "DioConf_DioChannel_DIO_UNUSED_P5_28 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P5_28 188U
#if (defined DioConf_DioChannel_DIO_UNUSED_P5_29)
#error "DioConf_DioChannel_DIO_UNUSED_P5_29 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P5_29 189U
#if (defined DioConf_DioChannel_DIO_UNUSED_P5_30)
#error "DioConf_DioChannel_DIO_UNUSED_P5_30 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P5_30 190U
#if (defined DioConf_DioChannel_DIO_UNUSED_P5_31)
#error "DioConf_DioChannel_DIO_UNUSED_P5_31 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P5_31 191U
#if (defined DioConf_DioChannel_DIO_MDO_TFT_BL1_EN)
#error "DioConf_DioChannel_DIO_MDO_TFT_BL1_EN already defined"
#endif
#define DioConf_DioChannel_DIO_MDO_TFT_BL1_EN 162U
#if (defined DioConf_DioChannel_DIO_UNUSED_P5_08)
#error "DioConf_DioChannel_DIO_UNUSED_P5_08 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P5_08 168U
#if (defined DioConf_DioChannel_DIO_UNUSED_P5_09)
#error "DioConf_DioChannel_DIO_UNUSED_P5_09 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P5_09 169U
#if (defined DioConf_DioChannel_DIO_UNUSED_P5_12)
#error "DioConf_DioChannel_DIO_UNUSED_P5_12 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P5_12 172U
#if (defined DioConf_DioChannel_DIO_UNUSED_P5_13)
#error "DioConf_DioChannel_DIO_UNUSED_P5_13 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P5_13 173U
#if (defined DioConf_DioChannel_DIO_UNUSED_P5_14)
#error "DioConf_DioChannel_DIO_UNUSED_P5_14 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P5_14 174U
#if (defined DioConf_DioChannel_DIO_MDO_BACKLIGHT_SCALE)
#error "DioConf_DioChannel_DIO_MDO_BACKLIGHT_SCALE already defined"
#endif
#define DioConf_DioChannel_DIO_MDO_BACKLIGHT_SCALE 175U
#if (defined DioConf_DioChannel_DIO_MDO_BAT_C_1)
#error "DioConf_DioChannel_DIO_MDO_BAT_C_1 already defined"
#endif
#define DioConf_DioChannel_DIO_MDO_BAT_C_1 177U
#if (defined DioConf_DioChannel_DIO_UNUSED_P5_22)
#error "DioConf_DioChannel_DIO_UNUSED_P5_22 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P5_22 182U
#if (defined DioConf_DioChannel_DIO_UNUSED_P5_21)
#error "DioConf_DioChannel_DIO_UNUSED_P5_21 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P5_21 181U
#if (defined DioConf_DioChannel_DIO_UNUSED_P5_05)
#error "DioConf_DioChannel_DIO_UNUSED_P5_05 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P5_05 165U
#if (defined DioConf_DioChannel_DIO_UNUSED_P5_18)
#error "DioConf_DioChannel_DIO_UNUSED_P5_18 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P5_18 178U
#if (defined DioConf_DioChannel_DIO_UNUSED_P5_19)
#error "DioConf_DioChannel_DIO_UNUSED_P5_19 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P5_19 179U
#if (defined DioConf_DioChannel_DIO_TEST_2)
#error "DioConf_DioChannel_DIO_TEST_2 already defined"
#endif
#define DioConf_DioChannel_DIO_TEST_2 163U
#if (defined DioConf_DioChannel_DIO_TEST_1)
#error "DioConf_DioChannel_DIO_TEST_1 already defined"
#endif
#define DioConf_DioChannel_DIO_TEST_1 164U
#if (defined DioConf_DioChannel_DIO_MDO_BACKLIGHT_DECORATION)
#error "DioConf_DioChannel_DIO_MDO_BACKLIGHT_DECORATION already defined"
#endif
#define DioConf_DioChannel_DIO_MDO_BACKLIGHT_DECORATION 176U
#if (defined DioConf_DioChannel_DIO_UNUSED_P6_00)
#error "DioConf_DioChannel_DIO_UNUSED_P6_00 already defined"
#endif
#define DioConf_DioChannel_DIO_UNUSED_P6_00 192U

/*------------------[DIO Driver Symbolic Channel Group Names ]---------------*/

/** Definition for supporting previous configuration settings.  */
#define DioChannelGroupCfg   Dio_ChannelGroupCfg


#if (defined DIO_NR_OF_CHANNEL_GROUPS)
#error "DIO_NR_OF_CHANNEL_GROUPS already defined"
#endif
#define DIO_NR_OF_CHANNEL_GROUPS 0U

/** This parameter defines the existence and the name of a callout function that is
 called each time an error was detected.
 The function has to have the following parameters: (ModuleId: uint16,
 InstanceId: uint8, ApiId: uint8, ErrorId: uint8) */
#define DIO_ERROR_CALLOUT_FUNCTION ErrorCalloutHandler

/*==================[type definitions]=======================================*/

/*==================[external function declarations]=========================*/

/*==================[internal function declarations]=========================*/

/*==================[external constants]=====================================*/

/*==================[internal constants]=====================================*/

/*==================[external data]==========================================*/

/*==================[internal data]==========================================*/

/*==================[external function definitions]==========================*/

/*==================[internal function definitions]==========================*/

#endif /* DIO_CFG_H */
/*==================[end of file]============================================*/
