#ifndef MCU_CFG_ARCH_H
#define MCU_CFG_ARCH_H 1

/** \brief AUTOSAR MCU Driver
 **
 ** This file contains API definitions of the configuration of the AUTOSAR module MCU that is
 ** target independent.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL40-DRV
 **
 ** (c) 2014-2017, Cypress Semiconductor Corporation. All rights reserved.
 **
 ** Warranty and Disclaimer
 **
 ** This software product is property of Cypress Semiconductor Corporation or
 ** its subsidiaries.
 ** Any use and/or distribution rights for this software product are provided
 ** only under the Cypress Software License Agreement.
 ** Any use and/or distribution of this software product not in accordance with
 ** the terms of the Cypress Software License Agreement are unauthorized and
 ** shall constitute an infringement of Cypress intellectual property rights.
*/


/*==================[inclusions]=============================================*/
#include <TSAutosar.h>     /* Cypress specific standard types */
#include <Std_Types.h>     /* AUTOSAR standard types */



/*==================[macros]=================================================*/

#define MCU_NUMBER_OF_RAM_CONFIG 1U

#define MCU_RAM_CONFIG_DATA \
{ \
  { /* McuRamSectorSettingConf_RUN */\
    0x0U, \
    0x80U, \
    0xffU \
  } \
}

#define MCU_NUMBER_OF_MODE_CONFIG 3U

#define MCU_MODE_CONFIG_DATA \
{ \
  { /* McuModeSettingConf_RUN */\
    MCU_MODE_RUN, /* ModeKind */\
    TRUE, /* CacheFlushEnable */\
    FALSE, /* PssSettingEnable */\
    { /* RegPssSetting */\
      14U, /* Exstbcnt */\
      14U, /* Ex5vrstcnt */\
      FALSE, /* Bramsc */\
      FALSE, /* Exvrstcnt*/\
      FALSE, /* Io35rstc */\
      FALSE, /* Io3rstc */\
      FALSE, /* Psspadctrl */\
      FALSE, /* Holdiopd2 */\
      FALSE, /* Holdiopd50 */\
      FALSE, /* Holdiopd51 */\
      FALSE, /* Holdiopd52 */\
      FALSE, /* Holdiopd53 */\
      FALSE, /* Holdiopd60 */\
      FALSE, /* Holdiopd61 */\
    }, \
    &Mcu_ClockConfigData[0],  /* ClockConfigPtr */ \
  }, \
  { /* McuModeSettingConf_PSS */\
    MCU_MODE_PSS, /* ModeKind */\
    TRUE, /* CacheFlushEnable */\
    TRUE, /* PssSettingEnable */\
    { /* RegPssSetting */\
      14U, /* Exstbcnt */\
      14U, /* Ex5vrstcnt */\
      FALSE, /* Bramsc */\
      FALSE, /* Exvrstcnt*/\
      TRUE, /* Io35rstc */\
      TRUE, /* Io3rstc */\
      FALSE, /* Psspadctrl */\
      TRUE, /* Holdiopd2 */\
      FALSE, /* Holdiopd50 */\
      FALSE, /* Holdiopd51 */\
      FALSE, /* Holdiopd52 */\
      FALSE, /* Holdiopd53 */\
      FALSE, /* Holdiopd60 */\
      FALSE, /* Holdiopd61 */\
    }, \
    &Mcu_ClockConfigData[1],  /* ClockConfigPtr */ \
  }, \
  { /* McuModeSettingConf_RUN_RTC */\
    MCU_MODE_RUN, /* ModeKind */\
    TRUE, /* CacheFlushEnable */\
    FALSE, /* PssSettingEnable */\
    { /* RegPssSetting */\
      14U, /* Exstbcnt */\
      14U, /* Ex5vrstcnt */\
      FALSE, /* Bramsc */\
      FALSE, /* Exvrstcnt*/\
      FALSE, /* Io35rstc */\
      FALSE, /* Io3rstc */\
      FALSE, /* Psspadctrl */\
      FALSE, /* Holdiopd2 */\
      FALSE, /* Holdiopd50 */\
      FALSE, /* Holdiopd51 */\
      FALSE, /* Holdiopd52 */\
      FALSE, /* Holdiopd53 */\
      FALSE, /* Holdiopd60 */\
      FALSE, /* Holdiopd61 */\
    }, \
    &Mcu_ClockConfigData[2],  /* ClockConfigPtr */ \
  } \
}

#define MCU_NUMBER_OF_CLOCK_CONFIG 3U

#define MCU_CLOCK_CONFIG_DATA \
{ \
  { /* McuClockSettingConfig_RUN */\
    &Mcu_ProfileConfigData[0], /* RunProfileConfigPtr */\
    NULL_PTR, /* PssProfileConfigPtr */\
    TRUE, /* CrOscillatorEnable */\
    { /* RegCrOscillator */\
      18U, /* Trf */\
      15U, /* Trc */\
      0U, /* Trv */\
      FALSE, /* Calibcsel */\
    }, \
    FALSE, /* ScrOscillatorEnable */\
    { /* RegScrOscillator */\
      0U, /* Trf */\
      0U, /* Trc */\
    }, \
    TRUE, /* MainOscillatorEnable */\
    { /* RegMainOscillator */\
      FALSE, /* Fcimen */\
      TRUE, /* Div2sel */\
      FALSE, /* Mampen */\
      1U, /* Mcgain */\
      FALSE, /* Mcmode */\
    }, \
    TRUE, /* SubOscillatorEnable */\
    { /* RegSubOscillator */\
      FALSE, /* Subport */\
      FALSE, /* Sampen */\
    }, \
    TRUE, /* ClockOutputEnable */\
    { /* RegClockOutput */\
      3U, /* Cksel */\
      0U, /* Ckoutdiv */\
      TRUE, /* Enclko */\
    }, \
    TRUE, /* PllClockStabilizationEnable */\
    { /* RegPllClockStabilization */\
      7U, /* Pllstabs */\
      7U, /* Sscgstabs */\
    }, \
    4U, /* ClockStabilizationNum */\
    &Mcu_ClockStabilizationConfigData[0], /*ClockStabilizationPtr */\
    3U, /* ClockSupervisorNum */\
    &Mcu_ClockSupervisorConfigData[0], /*ClockSupervisorPtr */\
    0U, /* ExPllNum */\
    NULL_PTR, /*ExPllPtr */\
    2U, /* ClockGearNum */\
    &Mcu_ClockGearConfigData[0], /*ClockGearPtr */\
  }, \
  { /* McuClockSettingConfig_PSS */\
    &Mcu_ProfileConfigData[2], /* RunProfileConfigPtr */\
    &Mcu_ProfileConfigData[1], /* PssProfileConfigPtr */\
    TRUE, /* CrOscillatorEnable */\
    { /* RegCrOscillator */\
      18U, /* Trf */\
      15U, /* Trc */\
      0U, /* Trv */\
      FALSE, /* Calibcsel */\
    }, \
    FALSE, /* ScrOscillatorEnable */\
    { /* RegScrOscillator */\
      0U, /* Trf */\
      0U, /* Trc */\
    }, \
    TRUE, /* MainOscillatorEnable */\
    { /* RegMainOscillator */\
      FALSE, /* Fcimen */\
      FALSE, /* Div2sel */\
      FALSE, /* Mampen */\
      1U, /* Mcgain */\
      FALSE, /* Mcmode */\
    }, \
    TRUE, /* SubOscillatorEnable */\
    { /* RegSubOscillator */\
      TRUE, /* Subport */\
      FALSE, /* Sampen */\
    }, \
    TRUE, /* ClockOutputEnable */\
    { /* RegClockOutput */\
      0U, /* Cksel */\
      7U, /* Ckoutdiv */\
      FALSE, /* Enclko */\
    }, \
    TRUE, /* PllClockStabilizationEnable */\
    { /* RegPllClockStabilization */\
      7U, /* Pllstabs */\
      7U, /* Sscgstabs */\
    }, \
    4U, /* ClockStabilizationNum */\
    &Mcu_ClockStabilizationConfigData[4], /*ClockStabilizationPtr */\
    3U, /* ClockSupervisorNum */\
    &Mcu_ClockSupervisorConfigData[3], /*ClockSupervisorPtr */\
    0U, /* ExPllNum */\
    NULL_PTR, /*ExPllPtr */\
    2U, /* ClockGearNum */\
    &Mcu_ClockGearConfigData[2], /*ClockGearPtr */\
  }, \
  { /* McuClockSettingConfig_RUN_RTC */\
    &Mcu_ProfileConfigData[3], /* RunProfileConfigPtr */\
    NULL_PTR, /* PssProfileConfigPtr */\
    TRUE, /* CrOscillatorEnable */\
    { /* RegCrOscillator */\
      18U, /* Trf */\
      15U, /* Trc */\
      0U, /* Trv */\
      FALSE, /* Calibcsel */\
    }, \
    FALSE, /* ScrOscillatorEnable */\
    { /* RegScrOscillator */\
      0U, /* Trf */\
      0U, /* Trc */\
    }, \
    TRUE, /* MainOscillatorEnable */\
    { /* RegMainOscillator */\
      FALSE, /* Fcimen */\
      TRUE, /* Div2sel */\
      FALSE, /* Mampen */\
      1U, /* Mcgain */\
      FALSE, /* Mcmode */\
    }, \
    TRUE, /* SubOscillatorEnable */\
    { /* RegSubOscillator */\
      TRUE, /* Subport */\
      FALSE, /* Sampen */\
    }, \
    TRUE, /* ClockOutputEnable */\
    { /* RegClockOutput */\
      3U, /* Cksel */\
      0U, /* Ckoutdiv */\
      TRUE, /* Enclko */\
    }, \
    TRUE, /* PllClockStabilizationEnable */\
    { /* RegPllClockStabilization */\
      7U, /* Pllstabs */\
      7U, /* Sscgstabs */\
    }, \
    4U, /* ClockStabilizationNum */\
    &Mcu_ClockStabilizationConfigData[8], /*ClockStabilizationPtr */\
    3U, /* ClockSupervisorNum */\
    &Mcu_ClockSupervisorConfigData[6], /*ClockSupervisorPtr */\
    0U, /* ExPllNum */\
    NULL_PTR, /*ExPllPtr */\
    2U, /* ClockGearNum */\
    &Mcu_ClockGearConfigData[4], /*ClockGearPtr */\
  } \
}


#define MCU_NUMBER_OF_CLOCK_STABILIZATION_CONFIG 12U

#define MCU_CLOCK_STABILIZATION_CONFIG_DATA \
{ \
  { \
    MCU_REG_IDX_SCT_FAST_CR, /* ClockStabilizationIndex */\
    MCU_SOURCE_CLOCK_FAST_CR, /* ClockStabilizationKind */\
    TRUE, /* ClockStabilizationEnable */\
    { /* RegClockStabilization */\
      30U, /* Cmpr */\
      6U, /* Pscl */\
    }, \
  },  \
  { \
    MCU_REG_IDX_SCT_SLOW_CR, /* ClockStabilizationIndex */\
    MCU_SOURCE_CLOCK_SLOW_CR, /* ClockStabilizationKind */\
    TRUE, /* ClockStabilizationEnable */\
    { /* RegClockStabilization */\
      1U, /* Cmpr */\
      6U, /* Pscl */\
    }, \
  },  \
  { \
    MCU_REG_IDX_SCT_MAIN, /* ClockStabilizationIndex */\
    MCU_SOURCE_CLOCK_MAIN, /* ClockStabilizationKind */\
    TRUE, /* ClockStabilizationEnable */\
    { /* RegClockStabilization */\
      512U, /* Cmpr */\
      6U, /* Pscl */\
    }, \
  },  \
  { \
    MCU_REG_IDX_SCT_SUB, /* ClockStabilizationIndex */\
    MCU_SOURCE_CLOCK_SUB, /* ClockStabilizationKind */\
    TRUE, /* ClockStabilizationEnable */\
    { /* RegClockStabilization */\
      4U, /* Cmpr */\
      6U, /* Pscl */\
    }, \
  },  \
  { \
    MCU_REG_IDX_SCT_FAST_CR, /* ClockStabilizationIndex */\
    MCU_SOURCE_CLOCK_FAST_CR, /* ClockStabilizationKind */\
    TRUE, /* ClockStabilizationEnable */\
    { /* RegClockStabilization */\
      30U, /* Cmpr */\
      6U, /* Pscl */\
    }, \
  },  \
  { \
    MCU_REG_IDX_SCT_SLOW_CR, /* ClockStabilizationIndex */\
    MCU_SOURCE_CLOCK_SLOW_CR, /* ClockStabilizationKind */\
    TRUE, /* ClockStabilizationEnable */\
    { /* RegClockStabilization */\
      1U, /* Cmpr */\
      6U, /* Pscl */\
    }, \
  },  \
  { \
    MCU_REG_IDX_SCT_MAIN, /* ClockStabilizationIndex */\
    MCU_SOURCE_CLOCK_MAIN, /* ClockStabilizationKind */\
    TRUE, /* ClockStabilizationEnable */\
    { /* RegClockStabilization */\
      512U, /* Cmpr */\
      6U, /* Pscl */\
    }, \
  },  \
  { \
    MCU_REG_IDX_SCT_SUB, /* ClockStabilizationIndex */\
    MCU_SOURCE_CLOCK_SUB, /* ClockStabilizationKind */\
    TRUE, /* ClockStabilizationEnable */\
    { /* RegClockStabilization */\
      4U, /* Cmpr */\
      6U, /* Pscl */\
    }, \
  },  \
  { \
    MCU_REG_IDX_SCT_FAST_CR, /* ClockStabilizationIndex */\
    MCU_SOURCE_CLOCK_FAST_CR, /* ClockStabilizationKind */\
    TRUE, /* ClockStabilizationEnable */\
    { /* RegClockStabilization */\
      30U, /* Cmpr */\
      6U, /* Pscl */\
    }, \
  },  \
  { \
    MCU_REG_IDX_SCT_SLOW_CR, /* ClockStabilizationIndex */\
    MCU_SOURCE_CLOCK_SLOW_CR, /* ClockStabilizationKind */\
    TRUE, /* ClockStabilizationEnable */\
    { /* RegClockStabilization */\
      1U, /* Cmpr */\
      6U, /* Pscl */\
    }, \
  },  \
  { \
    MCU_REG_IDX_SCT_MAIN, /* ClockStabilizationIndex */\
    MCU_SOURCE_CLOCK_MAIN, /* ClockStabilizationKind */\
    TRUE, /* ClockStabilizationEnable */\
    { /* RegClockStabilization */\
      512U, /* Cmpr */\
      6U, /* Pscl */\
    }, \
  },  \
  { \
    MCU_REG_IDX_SCT_SUB, /* ClockStabilizationIndex */\
    MCU_SOURCE_CLOCK_SUB, /* ClockStabilizationKind */\
    TRUE, /* ClockStabilizationEnable */\
    { /* RegClockStabilization */\
      4U, /* Cmpr */\
      6U, /* Pscl */\
    }, \
  }  \
}

#define MCU_NUMBER_OF_CLOCK_SUPERVISOR_CONFIG 9U

#define MCU_CLOCK_SUPERVISOR_CONFIG_DATA \
{ \
  { \
    MCU_REG_IDX_CSV_MAIN, /* ClockSupervisorIndex */\
    MCU_CSV_CLOCK_MAIN, /* ClockSupervisorKind */\
    TRUE , /* ClockSupervisorEnable */\
    { /* RegClockSupervisor */\
      8U, /* Lowthr */\
      16U, /* Upthr */\
      25U, /* Refclkwnd */\
      FALSE, /* Jdgsel */\
      0U, /* Refclksel */\
      2U, /* Refclkdiv */\
    }, \
  },  \
  { \
    MCU_REG_IDX_CSV_PLL0, /* ClockSupervisorIndex */\
    MCU_CSV_CLOCK_PLL0, /* ClockSupervisorKind */\
    TRUE , /* ClockSupervisorEnable */\
    { /* RegClockSupervisor */\
      8U, /* Lowthr */\
      16U, /* Upthr */\
      20U, /* Refclkwnd */\
      FALSE, /* Jdgsel */\
      0U, /* Refclksel */\
      2U, /* Refclkdiv */\
    }, \
  },  \
  { \
    MCU_REG_IDX_CSV_SSCG0, /* ClockSupervisorIndex */\
    MCU_CSV_CLOCK_SSCG0, /* ClockSupervisorKind */\
    TRUE , /* ClockSupervisorEnable */\
    { /* RegClockSupervisor */\
      0U, /* Lowthr */\
      0U, /* Upthr */\
      0U, /* Refclkwnd */\
      FALSE, /* Jdgsel */\
      0U, /* Refclksel */\
      2U, /* Refclkdiv */\
    }, \
  },  \
  { \
    MCU_REG_IDX_CSV_MAIN, /* ClockSupervisorIndex */\
    MCU_CSV_CLOCK_MAIN, /* ClockSupervisorKind */\
    TRUE , /* ClockSupervisorEnable */\
    { /* RegClockSupervisor */\
      8U, /* Lowthr */\
      16U, /* Upthr */\
      25U, /* Refclkwnd */\
      FALSE, /* Jdgsel */\
      0U, /* Refclksel */\
      2U, /* Refclkdiv */\
    }, \
  },  \
  { \
    MCU_REG_IDX_CSV_PLL0, /* ClockSupervisorIndex */\
    MCU_CSV_CLOCK_PLL0, /* ClockSupervisorKind */\
    TRUE , /* ClockSupervisorEnable */\
    { /* RegClockSupervisor */\
      8U, /* Lowthr */\
      16U, /* Upthr */\
      20U, /* Refclkwnd */\
      FALSE, /* Jdgsel */\
      0U, /* Refclksel */\
      2U, /* Refclkdiv */\
    }, \
  },  \
  { \
    MCU_REG_IDX_CSV_SSCG0, /* ClockSupervisorIndex */\
    MCU_CSV_CLOCK_SSCG0, /* ClockSupervisorKind */\
    TRUE , /* ClockSupervisorEnable */\
    { /* RegClockSupervisor */\
      0U, /* Lowthr */\
      0U, /* Upthr */\
      0U, /* Refclkwnd */\
      FALSE, /* Jdgsel */\
      0U, /* Refclksel */\
      2U, /* Refclkdiv */\
    }, \
  },  \
  { \
    MCU_REG_IDX_CSV_MAIN, /* ClockSupervisorIndex */\
    MCU_CSV_CLOCK_MAIN, /* ClockSupervisorKind */\
    TRUE , /* ClockSupervisorEnable */\
    { /* RegClockSupervisor */\
      8U, /* Lowthr */\
      16U, /* Upthr */\
      25U, /* Refclkwnd */\
      FALSE, /* Jdgsel */\
      0U, /* Refclksel */\
      2U, /* Refclkdiv */\
    }, \
  },  \
  { \
    MCU_REG_IDX_CSV_PLL0, /* ClockSupervisorIndex */\
    MCU_CSV_CLOCK_PLL0, /* ClockSupervisorKind */\
    TRUE , /* ClockSupervisorEnable */\
    { /* RegClockSupervisor */\
      8U, /* Lowthr */\
      16U, /* Upthr */\
      20U, /* Refclkwnd */\
      FALSE, /* Jdgsel */\
      0U, /* Refclksel */\
      2U, /* Refclkdiv */\
    }, \
  },  \
  { \
    MCU_REG_IDX_CSV_SSCG0, /* ClockSupervisorIndex */\
    MCU_CSV_CLOCK_SSCG0, /* ClockSupervisorKind */\
    TRUE , /* ClockSupervisorEnable */\
    { /* RegClockSupervisor */\
      0U, /* Lowthr */\
      0U, /* Upthr */\
      0U, /* Refclkwnd */\
      FALSE, /* Jdgsel */\
      0U, /* Refclksel */\
      2U, /* Refclkdiv */\
    }, \
  }  \
}

#define MCU_NUMBER_OF_CLOCK_GEAR_CONFIG 6U

#define MCU_CLOCK_GEAR_CONFIG_DATA \
{ \
  { \
    MCU_REG_IDX_CG_PLL0, /* ClockGearIndex */\
    MCU_SOURCE_CLOCK_PLL0, /* ClockGearKind */\
    TRUE , /* ClockGearEnable */\
    { /* RegClockGear */\
      0U, /* Pllcgssn */\
      0U, /* Pllcgstp */\
      255U, /* Pllcglp */\
      TRUE, /* Pllcgen */\
    }, \
  },  \
  { \
    MCU_REG_IDX_CG_SSCG0, /* ClockGearIndex */\
    MCU_SOURCE_CLOCK_SSCG0, /* ClockGearKind */\
    TRUE , /* ClockGearEnable */\
    { /* RegClockGear */\
      0U, /* Pllcgssn */\
      0U, /* Pllcgstp */\
      255U, /* Pllcglp */\
      TRUE, /* Pllcgen */\
    }, \
  },  \
  { \
    MCU_REG_IDX_CG_PLL0, /* ClockGearIndex */\
    MCU_SOURCE_CLOCK_PLL0, /* ClockGearKind */\
    TRUE , /* ClockGearEnable */\
    { /* RegClockGear */\
      0U, /* Pllcgssn */\
      0U, /* Pllcgstp */\
      255U, /* Pllcglp */\
      FALSE, /* Pllcgen */\
    }, \
  },  \
  { \
    MCU_REG_IDX_CG_SSCG0, /* ClockGearIndex */\
    MCU_SOURCE_CLOCK_SSCG0, /* ClockGearKind */\
    TRUE , /* ClockGearEnable */\
    { /* RegClockGear */\
      0U, /* Pllcgssn */\
      0U, /* Pllcgstp */\
      255U, /* Pllcglp */\
      FALSE, /* Pllcgen */\
    }, \
  },  \
  { \
    MCU_REG_IDX_CG_PLL0, /* ClockGearIndex */\
    MCU_SOURCE_CLOCK_PLL0, /* ClockGearKind */\
    TRUE , /* ClockGearEnable */\
    { /* RegClockGear */\
      0U, /* Pllcgssn */\
      0U, /* Pllcgstp */\
      255U, /* Pllcglp */\
      TRUE, /* Pllcgen */\
    }, \
  },  \
  { \
    MCU_REG_IDX_CG_SSCG0, /* ClockGearIndex */\
    MCU_SOURCE_CLOCK_SSCG0, /* ClockGearKind */\
    TRUE , /* ClockGearEnable */\
    { /* RegClockGear */\
      0U, /* Pllcgssn */\
      0U, /* Pllcgstp */\
      255U, /* Pllcglp */\
      TRUE, /* Pllcgen */\
    }, \
  }  \
}

#define MCU_NUMBER_OF_PROFILE_CONFIG 4U

#define MCU_PROFILE_CONFIG_DATA \
{ \
  { /* McuProfileSettings_RUN */\
    MCU_PROFILE_RUN, /* ProfileKind */\
    { /* RegProfile */\
      { /* RegProfilePd */\
        TRUE, /* Pd2en */\
        TRUE, /* Pd3en */\
        TRUE, /* Pd40en */\
        TRUE, /* Pd41en */\
        TRUE, /* Pd50en */\
        TRUE, /* Pd51en */\
        TRUE, /* Pd52en */\
        TRUE, /* Pd53en */\
        TRUE, /* Pd60en */\
        TRUE, /* Pd61en */\
      }, \
      { /* RegProfileRegulator */\
        FALSE, /* Rvsel */\
        FALSE, /* Rmsel */\
      }, \
      (Mcu_RegAddressType)(0x0U | MCU_SOURCE_CLOCK_FAST_CR | MCU_SOURCE_CLOCK_SLOW_CR | MCU_SOURCE_CLOCK_MAIN | MCU_SOURCE_CLOCK_SUB | MCU_SOURCE_CLOCK_PLL0 | MCU_SOURCE_CLOCK_PLL1 | MCU_SOURCE_CLOCK_PLL2 | MCU_SOURCE_CLOCK_PLL3 | MCU_SOURCE_CLOCK_SSCG0 | MCU_SOURCE_CLOCK_SSCG1 | MCU_SOURCE_CLOCK_SSCG2 | MCU_SOURCE_CLOCK_SSCG3), /* RegProfileSource */\
      (Mcu_RegAddressType)(0x0U), /* RegProfileCsv */\
      2U, /* ProfileLvdNum */\
      &Mcu_ProfileLvdConfigData[0], /* ProfileLvdPtr */\
      { /* RegProfileCdMcuc */\
        5U, /* Cdmcuccsl */\
        { /* Cdmcuch */\
          TRUE, /* Enclk */\
          3U, /* Div */\
        }, \
        { /* Cdmcucp */\
          TRUE, /* Enclk */\
          0U, /* Div */\
        } \
      }, \
      { /* RegFlashClock */\
        2U, /* Fawc */\
        9U, /* WfFawc */\
      }, \
      { /* RegProfileCd0 */\
        4U, /* Cd0csl */\
        { /* Cpu */\
          TRUE, /* Enclk */\
          0U, /* Div */\
        }, \
        { /* Atb */\
          TRUE, /* Enclk */\
          1U, /* Div */\
        }, \
        { /* Dbg */\
          TRUE, /* Enclk */\
          0U, /* Div */\
        }, \
        { /* Hpm */\
          TRUE, /* Enclk */\
          1U, /* Div */\
        }, \
        TRUE, /* Enclkhpm2 */\
        { /* Extbus */\
          TRUE, /* Enclk */\
          2U, /* Div */\
        }, \
        TRUE, /* Enclkmemc */\
        TRUE, /* Enclkdma */\
        { /* Sysc1 */\
          TRUE, /* Enclk */\
          2U, /* Div */\
        }, \
        { /* Happ0a0 */\
          TRUE, /* Enclk */\
          2U, /* Div */\
        }, \
        { /* Happ0a1 */\
          TRUE, /* Enclk */\
          0U, /* Div */\
        }, \
        { /* Happ1b0 */\
          TRUE, /* Enclk */\
          1U, /* Div */\
        }, \
        { /* Happ1b1 */\
          TRUE, /* Enclk */\
          1U, /* Div */\
        }, \
        TRUE, /* Enclkllpbm */\
        TRUE, /* Enclkllpbm2 */\
        { /* Lcp */\
          TRUE, /* Enclk */\
          2U, /* Div */\
        }, \
        { /* Lcp0 */\
          TRUE, /* Enclk */\
          5U, /* Div */\
        }, \
        { /* Lcp1 */\
          TRUE, /* Enclk */\
          5U, /* Div */\
        }, \
        { /* Lapp0 */\
          TRUE, /* Enclk */\
          5U, /* Div */\
        }, \
        { /* Lapp1 */\
          TRUE, /* Enclk */\
          5U, /* Div */\
        }, \
        { /* Lcp0a */\
          TRUE, /* Enclk */\
          3U, /* Div */\
          0U, /* Csl */\
        }, \
        { /* Lcp1a */\
          TRUE, /* Enclk */\
          3U, /* Div */\
          0U, /* Csl */\
        }, \
        { /* Lapp0a */\
          TRUE, /* Enclk */\
          5U, /* Div */\
          1U, /* Csl */\
        }, \
        { /* Lapp1a */\
          TRUE, /* Enclk */\
          5U, /* Div */\
          1U, /* Csl */\
        }, \
      }, \
      { /* RegProfileCdHsspi */\
        TRUE, /* Enclk */\
        0U, /* Div */\
        9U, /* Csl */\
      }, \
      { /* RegProfileCdTrc */\
        TRUE, /* Enclk */\
        4U, /* Div */\
        6U, /* Csl */\
      }, \
      5U, /* ProfileCdxNum */\
      &Mcu_ProfileCdxConfigData[0], /* ProfileCdxPtr */\
      4U, /* ProfilePllNum */\
      &Mcu_ProfilePllConfigData[0], /* ProfilePllPtr */\
      4U, /* ProfileSscgNum */\
      &Mcu_ProfileSscgConfigData[0], /* ProfileSscgPtr */\
    }, \
  },  \
  { /* McuProfileSettings_PSS_PSS */\
    MCU_PROFILE_PSS, /* ProfileKind */\
    { /* RegProfile */\
      { /* RegProfilePd */\
        FALSE, /* Pd2en */\
        FALSE, /* Pd3en */\
        TRUE, /* Pd40en */\
        TRUE, /* Pd41en */\
        FALSE, /* Pd50en */\
        FALSE, /* Pd51en */\
        FALSE, /* Pd52en */\
        FALSE, /* Pd53en */\
        FALSE, /* Pd60en */\
        FALSE, /* Pd61en */\
      }, \
      { /* RegProfileRegulator */\
        FALSE, /* Rvsel */\
        TRUE, /* Rmsel */\
      }, \
      (Mcu_RegAddressType)(0x0U | MCU_SOURCE_CLOCK_SLOW_CR | MCU_SOURCE_CLOCK_SUB), /* RegProfileSource */\
      (Mcu_RegAddressType)(0x0U), /* RegProfileCsv */\
      0U, /* ProfileLvdNum */\
      NULL_PTR, /* ProfileLvdPtr */\
      { /* RegProfileCdMcuc */\
        1U, /* Cdmcuccsl */\
        { /* Cdmcuch */\
          FALSE, /* Enclk */\
          0U, /* Div */\
        }, \
        { /* Cdmcucp */\
          TRUE, /* Enclk */\
          0U, /* Div */\
        } \
      }, \
      { /* RegFlashClock */\
        1U, /* Fawc */\
        9U, /* WfFawc */\
      }, \
      { /* RegProfileCd0 */\
        1U, /* Cd0csl */\
        { /* Cpu */\
          FALSE, /* Enclk */\
          0U, /* Div */\
        }, \
        { /* Atb */\
          FALSE, /* Enclk */\
          0U, /* Div */\
        }, \
        { /* Dbg */\
          FALSE, /* Enclk */\
          0U, /* Div */\
        }, \
        { /* Hpm */\
          FALSE, /* Enclk */\
          0U, /* Div */\
        }, \
        FALSE, /* Enclkhpm2 */\
        { /* Extbus */\
          FALSE, /* Enclk */\
          7U, /* Div */\
        }, \
        FALSE, /* Enclkmemc */\
        FALSE, /* Enclkdma */\
        { /* Sysc1 */\
          FALSE, /* Enclk */\
          0U, /* Div */\
        }, \
        { /* Happ0a0 */\
          FALSE, /* Enclk */\
          0U, /* Div */\
        }, \
        { /* Happ0a1 */\
          FALSE, /* Enclk */\
          0U, /* Div */\
        }, \
        { /* Happ1b0 */\
          FALSE, /* Enclk */\
          0U, /* Div */\
        }, \
        { /* Happ1b1 */\
          FALSE, /* Enclk */\
          0U, /* Div */\
        }, \
        FALSE, /* Enclkllpbm */\
        FALSE, /* Enclkllpbm2 */\
        { /* Lcp */\
          FALSE, /* Enclk */\
          0U, /* Div */\
        }, \
        { /* Lcp0 */\
          FALSE, /* Enclk */\
          0U, /* Div */\
        }, \
        { /* Lcp1 */\
          FALSE, /* Enclk */\
          0U, /* Div */\
        }, \
        { /* Lapp0 */\
          FALSE, /* Enclk */\
          0U, /* Div */\
        }, \
        { /* Lapp1 */\
          FALSE, /* Enclk */\
          0U, /* Div */\
        }, \
        { /* Lcp0a */\
          FALSE, /* Enclk */\
          0U, /* Div */\
          0U, /* Csl */\
        }, \
        { /* Lcp1a */\
          FALSE, /* Enclk */\
          0U, /* Div */\
          0U, /* Csl */\
        }, \
        { /* Lapp0a */\
          FALSE, /* Enclk */\
          0U, /* Div */\
          0U, /* Csl */\
        }, \
        { /* Lapp1a */\
          FALSE, /* Enclk */\
          0U, /* Div */\
          0U, /* Csl */\
        }, \
      }, \
      { /* RegProfileCdHsspi */\
        FALSE, /* Enclk */\
        31U, /* Div */\
        1U, /* Csl */\
      }, \
      { /* RegProfileCdTrc */\
        FALSE, /* Enclk */\
        0U, /* Div */\
        1U, /* Csl */\
      }, \
      5U, /* ProfileCdxNum */\
      &Mcu_ProfileCdxConfigData[5], /* ProfileCdxPtr */\
      4U, /* ProfilePllNum */\
      &Mcu_ProfilePllConfigData[4], /* ProfilePllPtr */\
      4U, /* ProfileSscgNum */\
      &Mcu_ProfileSscgConfigData[4], /* ProfileSscgPtr */\
    }, \
  },  \
  { /* McuProfileSettings_PSS_RUN */\
    MCU_PROFILE_RUN, /* ProfileKind */\
    { /* RegProfile */\
      { /* RegProfilePd */\
        TRUE, /* Pd2en */\
        TRUE, /* Pd3en */\
        TRUE, /* Pd40en */\
        TRUE, /* Pd41en */\
        TRUE, /* Pd50en */\
        TRUE, /* Pd51en */\
        TRUE, /* Pd52en */\
        TRUE, /* Pd53en */\
        TRUE, /* Pd60en */\
        TRUE, /* Pd61en */\
      }, \
      { /* RegProfileRegulator */\
        FALSE, /* Rvsel */\
        FALSE, /* Rmsel */\
      }, \
      (Mcu_RegAddressType)(0x0U | MCU_SOURCE_CLOCK_FAST_CR | MCU_SOURCE_CLOCK_SLOW_CR | MCU_SOURCE_CLOCK_MAIN | MCU_SOURCE_CLOCK_SUB), /* RegProfileSource */\
      (Mcu_RegAddressType)(0x0U), /* RegProfileCsv */\
      2U, /* ProfileLvdNum */\
      &Mcu_ProfileLvdConfigData[2], /* ProfileLvdPtr */\
      { /* RegProfileCdMcuc */\
        0U, /* Cdmcuccsl */\
        { /* Cdmcuch */\
          TRUE, /* Enclk */\
          0U, /* Div */\
        }, \
        { /* Cdmcucp */\
          TRUE, /* Enclk */\
          0U, /* Div */\
        } \
      }, \
      { /* RegFlashClock */\
        1U, /* Fawc */\
        9U, /* WfFawc */\
      }, \
      { /* RegProfileCd0 */\
        0U, /* Cd0csl */\
        { /* Cpu */\
          TRUE, /* Enclk */\
          0U, /* Div */\
        }, \
        { /* Atb */\
          TRUE, /* Enclk */\
          0U, /* Div */\
        }, \
        { /* Dbg */\
          TRUE, /* Enclk */\
          0U, /* Div */\
        }, \
        { /* Hpm */\
          TRUE, /* Enclk */\
          0U, /* Div */\
        }, \
        TRUE, /* Enclkhpm2 */\
        { /* Extbus */\
          TRUE, /* Enclk */\
          0U, /* Div */\
        }, \
        TRUE, /* Enclkmemc */\
        TRUE, /* Enclkdma */\
        { /* Sysc1 */\
          TRUE, /* Enclk */\
          0U, /* Div */\
        }, \
        { /* Happ0a0 */\
          TRUE, /* Enclk */\
          0U, /* Div */\
        }, \
        { /* Happ0a1 */\
          TRUE, /* Enclk */\
          0U, /* Div */\
        }, \
        { /* Happ1b0 */\
          TRUE, /* Enclk */\
          0U, /* Div */\
        }, \
        { /* Happ1b1 */\
          TRUE, /* Enclk */\
          0U, /* Div */\
        }, \
        TRUE, /* Enclkllpbm */\
        TRUE, /* Enclkllpbm2 */\
        { /* Lcp */\
          TRUE, /* Enclk */\
          0U, /* Div */\
        }, \
        { /* Lcp0 */\
          TRUE, /* Enclk */\
          0U, /* Div */\
        }, \
        { /* Lcp1 */\
          TRUE, /* Enclk */\
          0U, /* Div */\
        }, \
        { /* Lapp0 */\
          TRUE, /* Enclk */\
          0U, /* Div */\
        }, \
        { /* Lapp1 */\
          TRUE, /* Enclk */\
          0U, /* Div */\
        }, \
        { /* Lcp0a */\
          TRUE, /* Enclk */\
          0U, /* Div */\
          0U, /* Csl */\
        }, \
        { /* Lcp1a */\
          TRUE, /* Enclk */\
          0U, /* Div */\
          0U, /* Csl */\
        }, \
        { /* Lapp0a */\
          TRUE, /* Enclk */\
          0U, /* Div */\
          0U, /* Csl */\
        }, \
        { /* Lapp1a */\
          TRUE, /* Enclk */\
          0U, /* Div */\
          0U, /* Csl */\
        }, \
      }, \
      { /* RegProfileCdHsspi */\
        TRUE, /* Enclk */\
        0U, /* Div */\
        0U, /* Csl */\
      }, \
      { /* RegProfileCdTrc */\
        TRUE, /* Enclk */\
        0U, /* Div */\
        0U, /* Csl */\
      }, \
      5U, /* ProfileCdxNum */\
      &Mcu_ProfileCdxConfigData[10], /* ProfileCdxPtr */\
      4U, /* ProfilePllNum */\
      &Mcu_ProfilePllConfigData[8], /* ProfilePllPtr */\
      4U, /* ProfileSscgNum */\
      &Mcu_ProfileSscgConfigData[8], /* ProfileSscgPtr */\
    }, \
  },  \
  { /* McuProfileSettings_RUN */\
    MCU_PROFILE_RUN, /* ProfileKind */\
    { /* RegProfile */\
      { /* RegProfilePd */\
        TRUE, /* Pd2en */\
        TRUE, /* Pd3en */\
        TRUE, /* Pd40en */\
        TRUE, /* Pd41en */\
        TRUE, /* Pd50en */\
        TRUE, /* Pd51en */\
        TRUE, /* Pd52en */\
        TRUE, /* Pd53en */\
        TRUE, /* Pd60en */\
        TRUE, /* Pd61en */\
      }, \
      { /* RegProfileRegulator */\
        FALSE, /* Rvsel */\
        FALSE, /* Rmsel */\
      }, \
      (Mcu_RegAddressType)(0x0U | MCU_SOURCE_CLOCK_FAST_CR | MCU_SOURCE_CLOCK_SLOW_CR | MCU_SOURCE_CLOCK_MAIN | MCU_SOURCE_CLOCK_SUB | MCU_SOURCE_CLOCK_PLL0 | MCU_SOURCE_CLOCK_PLL1 | MCU_SOURCE_CLOCK_PLL2 | MCU_SOURCE_CLOCK_PLL3 | MCU_SOURCE_CLOCK_SSCG0 | MCU_SOURCE_CLOCK_SSCG1 | MCU_SOURCE_CLOCK_SSCG2 | MCU_SOURCE_CLOCK_SSCG3), /* RegProfileSource */\
      (Mcu_RegAddressType)(0x0U), /* RegProfileCsv */\
      2U, /* ProfileLvdNum */\
      &Mcu_ProfileLvdConfigData[4], /* ProfileLvdPtr */\
      { /* RegProfileCdMcuc */\
        5U, /* Cdmcuccsl */\
        { /* Cdmcuch */\
          TRUE, /* Enclk */\
          3U, /* Div */\
        }, \
        { /* Cdmcucp */\
          TRUE, /* Enclk */\
          0U, /* Div */\
        } \
      }, \
      { /* RegFlashClock */\
        2U, /* Fawc */\
        9U, /* WfFawc */\
      }, \
      { /* RegProfileCd0 */\
        4U, /* Cd0csl */\
        { /* Cpu */\
          TRUE, /* Enclk */\
          0U, /* Div */\
        }, \
        { /* Atb */\
          TRUE, /* Enclk */\
          1U, /* Div */\
        }, \
        { /* Dbg */\
          TRUE, /* Enclk */\
          0U, /* Div */\
        }, \
        { /* Hpm */\
          TRUE, /* Enclk */\
          1U, /* Div */\
        }, \
        TRUE, /* Enclkhpm2 */\
        { /* Extbus */\
          TRUE, /* Enclk */\
          2U, /* Div */\
        }, \
        TRUE, /* Enclkmemc */\
        TRUE, /* Enclkdma */\
        { /* Sysc1 */\
          TRUE, /* Enclk */\
          2U, /* Div */\
        }, \
        { /* Happ0a0 */\
          TRUE, /* Enclk */\
          2U, /* Div */\
        }, \
        { /* Happ0a1 */\
          TRUE, /* Enclk */\
          0U, /* Div */\
        }, \
        { /* Happ1b0 */\
          TRUE, /* Enclk */\
          1U, /* Div */\
        }, \
        { /* Happ1b1 */\
          TRUE, /* Enclk */\
          1U, /* Div */\
        }, \
        TRUE, /* Enclkllpbm */\
        TRUE, /* Enclkllpbm2 */\
        { /* Lcp */\
          TRUE, /* Enclk */\
          2U, /* Div */\
        }, \
        { /* Lcp0 */\
          TRUE, /* Enclk */\
          5U, /* Div */\
        }, \
        { /* Lcp1 */\
          TRUE, /* Enclk */\
          5U, /* Div */\
        }, \
        { /* Lapp0 */\
          TRUE, /* Enclk */\
          5U, /* Div */\
        }, \
        { /* Lapp1 */\
          TRUE, /* Enclk */\
          5U, /* Div */\
        }, \
        { /* Lcp0a */\
          TRUE, /* Enclk */\
          3U, /* Div */\
          0U, /* Csl */\
        }, \
        { /* Lcp1a */\
          TRUE, /* Enclk */\
          3U, /* Div */\
          0U, /* Csl */\
        }, \
        { /* Lapp0a */\
          TRUE, /* Enclk */\
          5U, /* Div */\
          1U, /* Csl */\
        }, \
        { /* Lapp1a */\
          TRUE, /* Enclk */\
          5U, /* Div */\
          1U, /* Csl */\
        }, \
      }, \
      { /* RegProfileCdHsspi */\
        TRUE, /* Enclk */\
        0U, /* Div */\
        9U, /* Csl */\
      }, \
      { /* RegProfileCdTrc */\
        TRUE, /* Enclk */\
        4U, /* Div */\
        6U, /* Csl */\
      }, \
      5U, /* ProfileCdxNum */\
      &Mcu_ProfileCdxConfigData[15], /* ProfileCdxPtr */\
      4U, /* ProfilePllNum */\
      &Mcu_ProfilePllConfigData[12], /* ProfilePllPtr */\
      4U, /* ProfileSscgNum */\
      &Mcu_ProfileSscgConfigData[12], /* ProfileSscgPtr */\
    }, \
  }   \
}

#define MCU_NUMBER_OF_PLL_CONFIG 16U

#define MCU_PROFILE_PLL_CONFIG_DATA \
{ \
  { /* McuProfileSettings_RUN */\
    MCU_REG_IDX_PLL_PLL0, /* ProfilePllIndex */\
    MCU_SOURCE_CLOCK_PLL0, /* ProfilePllKind */\
    TRUE , /* ProfilePllEnable */\
    { /* RegProfilePll */\
      1U, /* Plldivl */\
      1U, /* Plldivm */\
      120U, /* Plldivn */\
      FALSE, /* Pllisel */\
    }, \
  },  \
  { /* McuProfileSettings_RUN */\
    MCU_REG_IDX_PLL_PLL1, /* ProfilePllIndex */\
    MCU_SOURCE_CLOCK_PLL1, /* ProfilePllKind */\
    TRUE , /* ProfilePllEnable */\
    { /* RegProfilePll */\
      1U, /* Plldivl */\
      1U, /* Plldivm */\
      180U, /* Plldivn */\
      FALSE, /* Pllisel */\
    }, \
  },  \
  { /* McuProfileSettings_RUN */\
    MCU_REG_IDX_PLL_PLL2, /* ProfilePllIndex */\
    MCU_SOURCE_CLOCK_PLL2, /* ProfilePllKind */\
    TRUE , /* ProfilePllEnable */\
    { /* RegProfilePll */\
      1U, /* Plldivl */\
      2U, /* Plldivm */\
      123U, /* Plldivn */\
      FALSE, /* Pllisel */\
    }, \
  },  \
  { /* McuProfileSettings_RUN */\
    MCU_REG_IDX_PLL_PLL3, /* ProfilePllIndex */\
    MCU_SOURCE_CLOCK_PLL3, /* ProfilePllKind */\
    TRUE , /* ProfilePllEnable */\
    { /* RegProfilePll */\
      1U, /* Plldivl */\
      1U, /* Plldivm */\
      120U, /* Plldivn */\
      FALSE, /* Pllisel */\
    }, \
  },  \
  { /* McuProfileSettings_PSS_PSS */\
    MCU_REG_IDX_PLL_PLL0, /* ProfilePllIndex */\
    MCU_SOURCE_CLOCK_PLL0, /* ProfilePllKind */\
    TRUE , /* ProfilePllEnable */\
    { /* RegProfilePll */\
      1U, /* Plldivl */\
      1U, /* Plldivm */\
      120U, /* Plldivn */\
      FALSE, /* Pllisel */\
    }, \
  },  \
  { /* McuProfileSettings_PSS_PSS */\
    MCU_REG_IDX_PLL_PLL1, /* ProfilePllIndex */\
    MCU_SOURCE_CLOCK_PLL1, /* ProfilePllKind */\
    TRUE , /* ProfilePllEnable */\
    { /* RegProfilePll */\
      1U, /* Plldivl */\
      1U, /* Plldivm */\
      180U, /* Plldivn */\
      FALSE, /* Pllisel */\
    }, \
  },  \
  { /* McuProfileSettings_PSS_PSS */\
    MCU_REG_IDX_PLL_PLL2, /* ProfilePllIndex */\
    MCU_SOURCE_CLOCK_PLL2, /* ProfilePllKind */\
    TRUE , /* ProfilePllEnable */\
    { /* RegProfilePll */\
      1U, /* Plldivl */\
      2U, /* Plldivm */\
      123U, /* Plldivn */\
      FALSE, /* Pllisel */\
    }, \
  },  \
  { /* McuProfileSettings_PSS_PSS */\
    MCU_REG_IDX_PLL_PLL3, /* ProfilePllIndex */\
    MCU_SOURCE_CLOCK_PLL3, /* ProfilePllKind */\
    TRUE , /* ProfilePllEnable */\
    { /* RegProfilePll */\
      1U, /* Plldivl */\
      1U, /* Plldivm */\
      120U, /* Plldivn */\
      FALSE, /* Pllisel */\
    }, \
  },  \
  { /* McuProfileSettings_PSS_RUN */\
    MCU_REG_IDX_PLL_PLL0, /* ProfilePllIndex */\
    MCU_SOURCE_CLOCK_PLL0, /* ProfilePllKind */\
    TRUE , /* ProfilePllEnable */\
    { /* RegProfilePll */\
      1U, /* Plldivl */\
      1U, /* Plldivm */\
      120U, /* Plldivn */\
      FALSE, /* Pllisel */\
    }, \
  },  \
  { /* McuProfileSettings_PSS_RUN */\
    MCU_REG_IDX_PLL_PLL1, /* ProfilePllIndex */\
    MCU_SOURCE_CLOCK_PLL1, /* ProfilePllKind */\
    TRUE , /* ProfilePllEnable */\
    { /* RegProfilePll */\
      1U, /* Plldivl */\
      1U, /* Plldivm */\
      180U, /* Plldivn */\
      FALSE, /* Pllisel */\
    }, \
  },  \
  { /* McuProfileSettings_PSS_RUN */\
    MCU_REG_IDX_PLL_PLL2, /* ProfilePllIndex */\
    MCU_SOURCE_CLOCK_PLL2, /* ProfilePllKind */\
    TRUE , /* ProfilePllEnable */\
    { /* RegProfilePll */\
      1U, /* Plldivl */\
      2U, /* Plldivm */\
      123U, /* Plldivn */\
      FALSE, /* Pllisel */\
    }, \
  },  \
  { /* McuProfileSettings_PSS_RUN */\
    MCU_REG_IDX_PLL_PLL3, /* ProfilePllIndex */\
    MCU_SOURCE_CLOCK_PLL3, /* ProfilePllKind */\
    TRUE , /* ProfilePllEnable */\
    { /* RegProfilePll */\
      1U, /* Plldivl */\
      1U, /* Plldivm */\
      120U, /* Plldivn */\
      FALSE, /* Pllisel */\
    }, \
  },  \
  { /* McuProfileSettings_RUN */\
    MCU_REG_IDX_PLL_PLL0, /* ProfilePllIndex */\
    MCU_SOURCE_CLOCK_PLL0, /* ProfilePllKind */\
    TRUE , /* ProfilePllEnable */\
    { /* RegProfilePll */\
      1U, /* Plldivl */\
      1U, /* Plldivm */\
      120U, /* Plldivn */\
      FALSE, /* Pllisel */\
    }, \
  },  \
  { /* McuProfileSettings_RUN */\
    MCU_REG_IDX_PLL_PLL1, /* ProfilePllIndex */\
    MCU_SOURCE_CLOCK_PLL1, /* ProfilePllKind */\
    TRUE , /* ProfilePllEnable */\
    { /* RegProfilePll */\
      1U, /* Plldivl */\
      1U, /* Plldivm */\
      180U, /* Plldivn */\
      FALSE, /* Pllisel */\
    }, \
  },  \
  { /* McuProfileSettings_RUN */\
    MCU_REG_IDX_PLL_PLL2, /* ProfilePllIndex */\
    MCU_SOURCE_CLOCK_PLL2, /* ProfilePllKind */\
    TRUE , /* ProfilePllEnable */\
    { /* RegProfilePll */\
      1U, /* Plldivl */\
      2U, /* Plldivm */\
      123U, /* Plldivn */\
      FALSE, /* Pllisel */\
    }, \
  },  \
  { /* McuProfileSettings_RUN */\
    MCU_REG_IDX_PLL_PLL3, /* ProfilePllIndex */\
    MCU_SOURCE_CLOCK_PLL3, /* ProfilePllKind */\
    TRUE , /* ProfilePllEnable */\
    { /* RegProfilePll */\
      1U, /* Plldivl */\
      1U, /* Plldivm */\
      120U, /* Plldivn */\
      FALSE, /* Pllisel */\
    }, \
  }  \
}

#define MCU_NUMBER_OF_EXPLL_CONFIG 0U


#define MCU_NUMBER_OF_SSCG_CONFIG 16U

#define MCU_PROFILE_SSCG_CONFIG_DATA \
{ \
  { /* McuProfileSettings_RUN */\
    MCU_REG_IDX_SSCG_SSCG0, /* ProfileSscgIndex */\
    MCU_SOURCE_CLOCK_SSCG0, /* ProfileSscgKind */\
    TRUE , /* ProfileSscgEnable */\
    { /* RegProfileSscg */\
      1U, /* Sscgdivl */\
      1U, /* Sscgdivm */\
      116U, /* Sscgdivn */\
      FALSE, /* Sscgisel */\
      0x00F6U, /* Sscgrate */\
      FALSE, /* Sscgmode */\
      0U, /* Sscgfreq */\
      TRUE, /* Sscgssen */\
    }, \
  },  \
  { /* McuProfileSettings_RUN */\
    MCU_REG_IDX_SSCG_SSCG1, /* ProfileSscgIndex */\
    MCU_SOURCE_CLOCK_SSCG1, /* ProfileSscgKind */\
    TRUE , /* ProfileSscgEnable */\
    { /* RegProfileSscg */\
      0U, /* Sscgdivl */\
      2U, /* Sscgdivm */\
      100U, /* Sscgdivn */\
      FALSE, /* Sscgisel */\
      0x00F6U, /* Sscgrate */\
      TRUE, /* Sscgmode */\
      0U, /* Sscgfreq */\
      TRUE, /* Sscgssen */\
    }, \
  },  \
  { /* McuProfileSettings_RUN */\
    MCU_REG_IDX_SSCG_SSCG2, /* ProfileSscgIndex */\
    MCU_SOURCE_CLOCK_SSCG2, /* ProfileSscgKind */\
    TRUE , /* ProfileSscgEnable */\
    { /* RegProfileSscg */\
      1U, /* Sscgdivl */\
      1U, /* Sscgdivm */\
      100U, /* Sscgdivn */\
      FALSE, /* Sscgisel */\
      0x0029U, /* Sscgrate */\
      FALSE, /* Sscgmode */\
      0U, /* Sscgfreq */\
      FALSE, /* Sscgssen */\
    }, \
  },  \
  { /* McuProfileSettings_RUN */\
    MCU_REG_IDX_SSCG_SSCG3, /* ProfileSscgIndex */\
    MCU_SOURCE_CLOCK_SSCG3, /* ProfileSscgKind */\
    TRUE , /* ProfileSscgEnable */\
    { /* RegProfileSscg */\
      1U, /* Sscgdivl */\
      1U, /* Sscgdivm */\
      200U, /* Sscgdivn */\
      FALSE, /* Sscgisel */\
      0x00F6U, /* Sscgrate */\
      FALSE, /* Sscgmode */\
      0U, /* Sscgfreq */\
      TRUE, /* Sscgssen */\
    }, \
  },  \
  { /* McuProfileSettings_PSS_PSS */\
    MCU_REG_IDX_SSCG_SSCG0, /* ProfileSscgIndex */\
    MCU_SOURCE_CLOCK_SSCG0, /* ProfileSscgKind */\
    TRUE , /* ProfileSscgEnable */\
    { /* RegProfileSscg */\
      1U, /* Sscgdivl */\
      1U, /* Sscgdivm */\
      116U, /* Sscgdivn */\
      FALSE, /* Sscgisel */\
      0x00F6U, /* Sscgrate */\
      FALSE, /* Sscgmode */\
      0U, /* Sscgfreq */\
      TRUE, /* Sscgssen */\
    }, \
  },  \
  { /* McuProfileSettings_PSS_PSS */\
    MCU_REG_IDX_SSCG_SSCG1, /* ProfileSscgIndex */\
    MCU_SOURCE_CLOCK_SSCG1, /* ProfileSscgKind */\
    TRUE , /* ProfileSscgEnable */\
    { /* RegProfileSscg */\
      1U, /* Sscgdivl */\
      1U, /* Sscgdivm */\
      100U, /* Sscgdivn */\
      FALSE, /* Sscgisel */\
      0x00F6U, /* Sscgrate */\
      TRUE, /* Sscgmode */\
      0U, /* Sscgfreq */\
      TRUE, /* Sscgssen */\
    }, \
  },  \
  { /* McuProfileSettings_PSS_PSS */\
    MCU_REG_IDX_SSCG_SSCG2, /* ProfileSscgIndex */\
    MCU_SOURCE_CLOCK_SSCG2, /* ProfileSscgKind */\
    TRUE , /* ProfileSscgEnable */\
    { /* RegProfileSscg */\
      1U, /* Sscgdivl */\
      1U, /* Sscgdivm */\
      100U, /* Sscgdivn */\
      FALSE, /* Sscgisel */\
      0x0029U, /* Sscgrate */\
      FALSE, /* Sscgmode */\
      0U, /* Sscgfreq */\
      FALSE, /* Sscgssen */\
    }, \
  },  \
  { /* McuProfileSettings_PSS_PSS */\
    MCU_REG_IDX_SSCG_SSCG3, /* ProfileSscgIndex */\
    MCU_SOURCE_CLOCK_SSCG3, /* ProfileSscgKind */\
    TRUE , /* ProfileSscgEnable */\
    { /* RegProfileSscg */\
      1U, /* Sscgdivl */\
      1U, /* Sscgdivm */\
      200U, /* Sscgdivn */\
      FALSE, /* Sscgisel */\
      0x00F6U, /* Sscgrate */\
      FALSE, /* Sscgmode */\
      0U, /* Sscgfreq */\
      TRUE, /* Sscgssen */\
    }, \
  },  \
  { /* McuProfileSettings_PSS_RUN */\
    MCU_REG_IDX_SSCG_SSCG0, /* ProfileSscgIndex */\
    MCU_SOURCE_CLOCK_SSCG0, /* ProfileSscgKind */\
    TRUE , /* ProfileSscgEnable */\
    { /* RegProfileSscg */\
      1U, /* Sscgdivl */\
      1U, /* Sscgdivm */\
      116U, /* Sscgdivn */\
      FALSE, /* Sscgisel */\
      0x00F6U, /* Sscgrate */\
      FALSE, /* Sscgmode */\
      0U, /* Sscgfreq */\
      TRUE, /* Sscgssen */\
    }, \
  },  \
  { /* McuProfileSettings_PSS_RUN */\
    MCU_REG_IDX_SSCG_SSCG1, /* ProfileSscgIndex */\
    MCU_SOURCE_CLOCK_SSCG1, /* ProfileSscgKind */\
    TRUE , /* ProfileSscgEnable */\
    { /* RegProfileSscg */\
      1U, /* Sscgdivl */\
      1U, /* Sscgdivm */\
      100U, /* Sscgdivn */\
      FALSE, /* Sscgisel */\
      0x00F6U, /* Sscgrate */\
      TRUE, /* Sscgmode */\
      0U, /* Sscgfreq */\
      TRUE, /* Sscgssen */\
    }, \
  },  \
  { /* McuProfileSettings_PSS_RUN */\
    MCU_REG_IDX_SSCG_SSCG2, /* ProfileSscgIndex */\
    MCU_SOURCE_CLOCK_SSCG2, /* ProfileSscgKind */\
    TRUE , /* ProfileSscgEnable */\
    { /* RegProfileSscg */\
      1U, /* Sscgdivl */\
      1U, /* Sscgdivm */\
      100U, /* Sscgdivn */\
      FALSE, /* Sscgisel */\
      0x0029U, /* Sscgrate */\
      FALSE, /* Sscgmode */\
      0U, /* Sscgfreq */\
      FALSE, /* Sscgssen */\
    }, \
  },  \
  { /* McuProfileSettings_PSS_RUN */\
    MCU_REG_IDX_SSCG_SSCG3, /* ProfileSscgIndex */\
    MCU_SOURCE_CLOCK_SSCG3, /* ProfileSscgKind */\
    TRUE , /* ProfileSscgEnable */\
    { /* RegProfileSscg */\
      1U, /* Sscgdivl */\
      1U, /* Sscgdivm */\
      200U, /* Sscgdivn */\
      FALSE, /* Sscgisel */\
      0x00F6U, /* Sscgrate */\
      FALSE, /* Sscgmode */\
      0U, /* Sscgfreq */\
      TRUE, /* Sscgssen */\
    }, \
  },  \
  { /* McuProfileSettings_RUN */\
    MCU_REG_IDX_SSCG_SSCG0, /* ProfileSscgIndex */\
    MCU_SOURCE_CLOCK_SSCG0, /* ProfileSscgKind */\
    TRUE , /* ProfileSscgEnable */\
    { /* RegProfileSscg */\
      1U, /* Sscgdivl */\
      1U, /* Sscgdivm */\
      116U, /* Sscgdivn */\
      FALSE, /* Sscgisel */\
      0x00F6U, /* Sscgrate */\
      FALSE, /* Sscgmode */\
      0U, /* Sscgfreq */\
      TRUE, /* Sscgssen */\
    }, \
  },  \
  { /* McuProfileSettings_RUN */\
    MCU_REG_IDX_SSCG_SSCG1, /* ProfileSscgIndex */\
    MCU_SOURCE_CLOCK_SSCG1, /* ProfileSscgKind */\
    TRUE , /* ProfileSscgEnable */\
    { /* RegProfileSscg */\
      0U, /* Sscgdivl */\
      2U, /* Sscgdivm */\
      84U, /* Sscgdivn */\
      FALSE, /* Sscgisel */\
      0x00F6U, /* Sscgrate */\
      TRUE, /* Sscgmode */\
      0U, /* Sscgfreq */\
      TRUE, /* Sscgssen */\
    }, \
  },  \
  { /* McuProfileSettings_RUN */\
    MCU_REG_IDX_SSCG_SSCG2, /* ProfileSscgIndex */\
    MCU_SOURCE_CLOCK_SSCG2, /* ProfileSscgKind */\
    TRUE , /* ProfileSscgEnable */\
    { /* RegProfileSscg */\
      1U, /* Sscgdivl */\
      1U, /* Sscgdivm */\
      100U, /* Sscgdivn */\
      FALSE, /* Sscgisel */\
      0x0029U, /* Sscgrate */\
      FALSE, /* Sscgmode */\
      0U, /* Sscgfreq */\
      FALSE, /* Sscgssen */\
    }, \
  },  \
  { /* McuProfileSettings_RUN */\
    MCU_REG_IDX_SSCG_SSCG3, /* ProfileSscgIndex */\
    MCU_SOURCE_CLOCK_SSCG3, /* ProfileSscgKind */\
    TRUE , /* ProfileSscgEnable */\
    { /* RegProfileSscg */\
      1U, /* Sscgdivl */\
      1U, /* Sscgdivm */\
      200U, /* Sscgdivn */\
      FALSE, /* Sscgisel */\
      0x00F6U, /* Sscgrate */\
      FALSE, /* Sscgmode */\
      0U, /* Sscgfreq */\
      TRUE, /* Sscgssen */\
    }, \
  }  \
}

#define MCU_NUMBER_OF_CDX_CONFIG 20U

#define MCU_PROFILE_CDX_CONFIG_DATA \
{ \
  { /* McuProfileSettings_RUN : MCU_CD_1 */\
    MCU_CD_1, /* ProfileCdxKind */\
    TRUE , /* ProfileCdxEnable */\
    { /* RegProfileCdx */\
      { /* Cdx */\
        TRUE, /* Enclk */\
        0U, /* Div */\
        11U, /* Csl */\
      }, \
      { /* Cdxa0 */\
        TRUE, /* Enclk */\
        3U, /* Div */\
      }, \
      { /* Cdxa1 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxb0 */\
        TRUE, /* Enclk */\
        3U, /* Div */\
      }, \
      { /* Cdxb1 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
    }, \
  },  \
  { /* McuProfileSettings_RUN : MCU_CD_2 */\
    MCU_CD_2, /* ProfileCdxKind */\
    TRUE , /* ProfileCdxEnable */\
    { /* RegProfileCdx */\
      { /* Cdx */\
        TRUE, /* Enclk */\
        0U, /* Div */\
        5U, /* Csl */\
      }, \
      { /* Cdxa0 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxa1 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxb0 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxb1 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
    }, \
  },  \
  { /* McuProfileSettings_RUN : MCU_CD_3 */\
    MCU_CD_3, /* ProfileCdxKind */\
    TRUE , /* ProfileCdxEnable */\
    { /* RegProfileCdx */\
      { /* Cdx */\
        TRUE, /* Enclk */\
        0U, /* Div */\
        10U, /* Csl */\
      }, \
      { /* Cdxa0 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxa1 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxb0 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxb1 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
    }, \
  },  \
  { /* McuProfileSettings_RUN : MCU_CD_4 */\
    MCU_CD_4, /* ProfileCdxKind */\
    TRUE , /* ProfileCdxEnable */\
    { /* RegProfileCdx */\
      { /* Cdx */\
        TRUE, /* Enclk */\
        0U, /* Div */\
        6U, /* Csl */\
      }, \
      { /* Cdxa0 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxa1 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxb0 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxb1 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
    }, \
  },  \
  { /* McuProfileSettings_RUN : MCU_CD_5 */\
    MCU_CD_5, /* ProfileCdxKind */\
    TRUE , /* ProfileCdxEnable */\
    { /* RegProfileCdx */\
      { /* Cdx */\
        TRUE, /* Enclk */\
        0U, /* Div */\
        7U, /* Csl */\
      }, \
      { /* Cdxa0 */\
        TRUE, /* Enclk */\
        1U, /* Div */\
      }, \
      { /* Cdxa1 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxb0 */\
        TRUE, /* Enclk */\
        3U, /* Div */\
      }, \
      { /* Cdxb1 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
    }, \
  },  \
  { /* McuProfileSettings_PSS_PSS : MCU_CD_1 */\
    MCU_CD_1, /* ProfileCdxKind */\
    TRUE , /* ProfileCdxEnable */\
    { /* RegProfileCdx */\
      { /* Cdx */\
        FALSE, /* Enclk */\
        31U, /* Div */\
        1U, /* Csl */\
      }, \
      { /* Cdxa0 */\
        FALSE, /* Enclk */\
        15U, /* Div */\
      }, \
      { /* Cdxa1 */\
        FALSE, /* Enclk */\
        15U, /* Div */\
      }, \
      { /* Cdxb0 */\
        FALSE, /* Enclk */\
        15U, /* Div */\
      }, \
      { /* Cdxb1 */\
        FALSE, /* Enclk */\
        15U, /* Div */\
      }, \
    }, \
  },  \
  { /* McuProfileSettings_PSS_PSS : MCU_CD_2 */\
    MCU_CD_2, /* ProfileCdxKind */\
    TRUE , /* ProfileCdxEnable */\
    { /* RegProfileCdx */\
      { /* Cdx */\
        FALSE, /* Enclk */\
        31U, /* Div */\
        1U, /* Csl */\
      }, \
      { /* Cdxa0 */\
        FALSE, /* Enclk */\
        15U, /* Div */\
      }, \
      { /* Cdxa1 */\
        FALSE, /* Enclk */\
        15U, /* Div */\
      }, \
      { /* Cdxb0 */\
        FALSE, /* Enclk */\
        15U, /* Div */\
      }, \
      { /* Cdxb1 */\
        FALSE, /* Enclk */\
        15U, /* Div */\
      }, \
    }, \
  },  \
  { /* McuProfileSettings_PSS_PSS : MCU_CD_3 */\
    MCU_CD_3, /* ProfileCdxKind */\
    TRUE , /* ProfileCdxEnable */\
    { /* RegProfileCdx */\
      { /* Cdx */\
        FALSE, /* Enclk */\
        31U, /* Div */\
        1U, /* Csl */\
      }, \
      { /* Cdxa0 */\
        FALSE, /* Enclk */\
        15U, /* Div */\
      }, \
      { /* Cdxa1 */\
        FALSE, /* Enclk */\
        15U, /* Div */\
      }, \
      { /* Cdxb0 */\
        FALSE, /* Enclk */\
        15U, /* Div */\
      }, \
      { /* Cdxb1 */\
        FALSE, /* Enclk */\
        15U, /* Div */\
      }, \
    }, \
  },  \
  { /* McuProfileSettings_PSS_PSS : MCU_CD_4 */\
    MCU_CD_4, /* ProfileCdxKind */\
    TRUE , /* ProfileCdxEnable */\
    { /* RegProfileCdx */\
      { /* Cdx */\
        FALSE, /* Enclk */\
        31U, /* Div */\
        1U, /* Csl */\
      }, \
      { /* Cdxa0 */\
        FALSE, /* Enclk */\
        15U, /* Div */\
      }, \
      { /* Cdxa1 */\
        FALSE, /* Enclk */\
        15U, /* Div */\
      }, \
      { /* Cdxb0 */\
        FALSE, /* Enclk */\
        15U, /* Div */\
      }, \
      { /* Cdxb1 */\
        FALSE, /* Enclk */\
        15U, /* Div */\
      }, \
    }, \
  },  \
  { /* McuProfileSettings_PSS_PSS : MCU_CD_5 */\
    MCU_CD_5, /* ProfileCdxKind */\
    TRUE , /* ProfileCdxEnable */\
    { /* RegProfileCdx */\
      { /* Cdx */\
        FALSE, /* Enclk */\
        31U, /* Div */\
        1U, /* Csl */\
      }, \
      { /* Cdxa0 */\
        FALSE, /* Enclk */\
        15U, /* Div */\
      }, \
      { /* Cdxa1 */\
        FALSE, /* Enclk */\
        15U, /* Div */\
      }, \
      { /* Cdxb0 */\
        FALSE, /* Enclk */\
        15U, /* Div */\
      }, \
      { /* Cdxb1 */\
        FALSE, /* Enclk */\
        15U, /* Div */\
      }, \
    }, \
  },  \
  { /* McuProfileSettings_PSS_RUN : MCU_CD_1 */\
    MCU_CD_1, /* ProfileCdxKind */\
    TRUE , /* ProfileCdxEnable */\
    { /* RegProfileCdx */\
      { /* Cdx */\
        TRUE, /* Enclk */\
        0U, /* Div */\
        0U, /* Csl */\
      }, \
      { /* Cdxa0 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxa1 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxb0 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxb1 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
    }, \
  },  \
  { /* McuProfileSettings_PSS_RUN : MCU_CD_2 */\
    MCU_CD_2, /* ProfileCdxKind */\
    TRUE , /* ProfileCdxEnable */\
    { /* RegProfileCdx */\
      { /* Cdx */\
        TRUE, /* Enclk */\
        0U, /* Div */\
        0U, /* Csl */\
      }, \
      { /* Cdxa0 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxa1 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxb0 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxb1 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
    }, \
  },  \
  { /* McuProfileSettings_PSS_RUN : MCU_CD_3 */\
    MCU_CD_3, /* ProfileCdxKind */\
    TRUE , /* ProfileCdxEnable */\
    { /* RegProfileCdx */\
      { /* Cdx */\
        TRUE, /* Enclk */\
        0U, /* Div */\
        0U, /* Csl */\
      }, \
      { /* Cdxa0 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxa1 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxb0 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxb1 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
    }, \
  },  \
  { /* McuProfileSettings_PSS_RUN : MCU_CD_4 */\
    MCU_CD_4, /* ProfileCdxKind */\
    TRUE , /* ProfileCdxEnable */\
    { /* RegProfileCdx */\
      { /* Cdx */\
        TRUE, /* Enclk */\
        0U, /* Div */\
        0U, /* Csl */\
      }, \
      { /* Cdxa0 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxa1 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxb0 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxb1 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
    }, \
  },  \
  { /* McuProfileSettings_PSS_RUN : MCU_CD_5 */\
    MCU_CD_5, /* ProfileCdxKind */\
    TRUE , /* ProfileCdxEnable */\
    { /* RegProfileCdx */\
      { /* Cdx */\
        TRUE, /* Enclk */\
        0U, /* Div */\
        15U, /* Csl */\
      }, \
      { /* Cdxa0 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxa1 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxb0 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxb1 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
    }, \
  },  \
  { /* McuProfileSettings_RUN : MCU_CD_1 */\
    MCU_CD_1, /* ProfileCdxKind */\
    TRUE , /* ProfileCdxEnable */\
    { /* RegProfileCdx */\
      { /* Cdx */\
        TRUE, /* Enclk */\
        0U, /* Div */\
        11U, /* Csl */\
      }, \
      { /* Cdxa0 */\
        TRUE, /* Enclk */\
        3U, /* Div */\
      }, \
      { /* Cdxa1 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxb0 */\
        TRUE, /* Enclk */\
        3U, /* Div */\
      }, \
      { /* Cdxb1 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
    }, \
  },  \
  { /* McuProfileSettings_RUN : MCU_CD_2 */\
    MCU_CD_2, /* ProfileCdxKind */\
    TRUE , /* ProfileCdxEnable */\
    { /* RegProfileCdx */\
      { /* Cdx */\
        TRUE, /* Enclk */\
        0U, /* Div */\
        5U, /* Csl */\
      }, \
      { /* Cdxa0 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxa1 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxb0 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxb1 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
    }, \
  },  \
  { /* McuProfileSettings_RUN : MCU_CD_3 */\
    MCU_CD_3, /* ProfileCdxKind */\
    TRUE , /* ProfileCdxEnable */\
    { /* RegProfileCdx */\
      { /* Cdx */\
        TRUE, /* Enclk */\
        0U, /* Div */\
        10U, /* Csl */\
      }, \
      { /* Cdxa0 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxa1 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxb0 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxb1 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
    }, \
  },  \
  { /* McuProfileSettings_RUN : MCU_CD_4 */\
    MCU_CD_4, /* ProfileCdxKind */\
    TRUE , /* ProfileCdxEnable */\
    { /* RegProfileCdx */\
      { /* Cdx */\
        TRUE, /* Enclk */\
        0U, /* Div */\
        6U, /* Csl */\
      }, \
      { /* Cdxa0 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxa1 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxb0 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxb1 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
    }, \
  },  \
  { /* McuProfileSettings_RUN : MCU_CD_5 */\
    MCU_CD_5, /* ProfileCdxKind */\
    TRUE , /* ProfileCdxEnable */\
    { /* RegProfileCdx */\
      { /* Cdx */\
        TRUE, /* Enclk */\
        0U, /* Div */\
        7U, /* Csl */\
      }, \
      { /* Cdxa0 */\
        TRUE, /* Enclk */\
        1U, /* Div */\
      }, \
      { /* Cdxa1 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
      { /* Cdxb0 */\
        TRUE, /* Enclk */\
        3U, /* Div */\
      }, \
      { /* Cdxb1 */\
        TRUE, /* Enclk */\
        0U, /* Div */\
      }, \
    }, \
  }  \
}

#define MCU_NUMBER_OF_LVD_CONFIG 6U

#define MCU_PROFILE_LVD_CONFIG_DATA \
{ \
  { /* McuProfileSettings_RUN : MCU_LVD_EXTERNAL */\
    MCU_LVD_LVDH1, /* ProfileLvdKind */\
    TRUE , /* ProfileLvdEnable */\
    {  /* RegProfileLvd */\
      TRUE, /* Lvde */\
      6U, /* Lvdv */\
      FALSE, /* Lvds */\
    }, \
  },  \
  { /* McuProfileSettings_RUN : MCU_LVD_INTERNAL */\
    MCU_LVD_LVDL1, /* ProfileLvdKind */\
    TRUE , /* ProfileLvdEnable */\
    {  /* RegProfileLvd */\
      TRUE, /* Lvde */\
      2U, /* Lvdv */\
      FALSE, /* Lvds */\
    }, \
  },  \
  { /* McuProfileSettings_PSS_RUN : MCU_LVD_INTERNAL */\
    MCU_LVD_LVDL1, /* ProfileLvdKind */\
    TRUE , /* ProfileLvdEnable */\
    {  /* RegProfileLvd */\
      FALSE, /* Lvde */\
      2U, /* Lvdv */\
      TRUE, /* Lvds */\
    }, \
  },  \
  { /* McuProfileSettings_PSS_RUN : MCU_LVD_EXTERNAL */\
    MCU_LVD_LVDH1, /* ProfileLvdKind */\
    TRUE , /* ProfileLvdEnable */\
    {  /* RegProfileLvd */\
      FALSE, /* Lvde */\
      6U, /* Lvdv */\
      TRUE, /* Lvds */\
    }, \
  },  \
  { /* McuProfileSettings_RUN : MCU_LVD_EXTERNAL */\
    MCU_LVD_LVDH1, /* ProfileLvdKind */\
    TRUE , /* ProfileLvdEnable */\
    {  /* RegProfileLvd */\
      TRUE, /* Lvde */\
      6U, /* Lvdv */\
      FALSE, /* Lvds */\
    }, \
  },  \
  { /* McuProfileSettings_RUN : MCU_LVD_INTERNAL */\
    MCU_LVD_LVDL1, /* ProfileLvdKind */\
    TRUE , /* ProfileLvdEnable */\
    {  /* RegProfileLvd */\
      TRUE, /* Lvde */\
      2U, /* Lvdv */\
      FALSE, /* Lvds */\
    }, \
  }  \
}

#define MCU_NUMBER_OF_CSV 12U

#define MCU_NUMBER_OF_SCT 4U

#define MCU_NUMBER_OF_CG 8U

#define MCU_NUMBER_OF_PLL 4U

#define MCU_NUMBER_OF_SSCG 4U


  
#ifndef __MCAL_IO_DEFINE
#define MCU_REG_BASE_ADDR_DATA \
{ \
  ((Mcu_RegClockRegisterType *) 0xB0600600uL), /* ClockBase */\
  ((Mcu_RegCsvRegisterBaseType *) 0xB0600300uL), /* CsvBase */\
  { /* SctBase */\
    ((Mcu_RegSctRegisterType *)0xB0600400uL), /* FAST_CR */\
    ((Mcu_RegSctRegisterType *)0xB0600480uL), /* SLOW_CR */\
    ((Mcu_RegSctRegisterType *)0xB0600500uL), /* MAIN */\
    ((Mcu_RegSctRegisterType *)0xB0600580uL), /* SUB */\
  }, \
  ((Mcu_RegSpecialRegisterType *) 0xB0600680uL), /* SpecialBase */\
  ((Mcu_RegAddressType *) 0xB0600000uL), /* Sysc0ProtKeyBase */\
  ((Mcu_RegSysc0RegisterType *) 0xB0600080uL), /* Sysc0RunBase */\
  ((Mcu_RegAddressType *) 0xB06000FCuL), /* Sysc0RunTrgBase */\
  ((Mcu_RegSysc0RegisterType *) 0xB0600100uL), /* Sysc0PssBase */\
  ((Mcu_RegAddressType *) 0xB060017CuL), /* Sysc0PssEnBase */\
  ((Mcu_RegSysc0RegisterType *) 0xB0600180uL), /* Sysc0AppBase */\
  ((Mcu_RegSysc0RegisterType *) 0xB0600200uL), /* Sysc0StsBase */\
  ((Mcu_RegAddressType *) 0xB0300000uL), /* Sysc1ProtKeyBase */\
  ((Mcu_RegSysc1RegisterType *) 0xB0300080uL), /* Sysc1RunBase */\
  ((Mcu_RegAddressType *) 0xB03000FCuL), /* Sysc1RunEnBase */\
  ((Mcu_RegSysc1RegisterType *) 0xB0300100uL), /* Sysc1PssBase */\
  ((Mcu_RegAddressType *) 0xB030017CuL), /* Sysc1PssEnBase */\
  ((Mcu_RegSysc1RegisterType *) 0xB0300180uL), /* Sysc1AppBase */\
  ((Mcu_RegSysc1RegisterType *) 0xB0300200uL), /* Sysc1StsBase */\
  ((Mcu_RegAddressType *) 0xB0411000uL), /* FlashProtKeyBase */\
  ((Mcu_RegFlashRegisterType *) 0xB0411008uL), /* FlashBase */\
  ((Mcu_RegAddressType *) NULL_PTR), /* WorkFlashProtKeyBase */\
  ((Mcu_RegWorkFlashRegisterType *) NULL_PTR), /* WorkFlashBase */\
  ((Mcu_RegAddressType *) 0xB0600380uL), /* ResetCntrBase */\
  ((Mcu_RegResetRegisterType *) 0xB0600390uL), /* ResetBase */\
  ((Mcu_RegSystemRegisterType *) 0xB0600288uL), /* SystemBase */\
  ((Mcu_RegNmiRegisterType *) 0xB0400C40uL), /* NmiBase */\
  ((Mcu_RegAddressType *) 0xB0600630uL), /* ClockMonitorBase */\
  FALSE, /* ScrCntrFlag */\
  ((Mcu_RegExPllRegisterType *) NULL_PTR) /* ExPllBase */\
}
#else
#define MCU_REG_BASE_ADDR_DATA \
{ \
  &Mcu_ClockRegister,         /* ClockBase */\
  &Mcu_CsvRegister,           /* CsvBase */\
  { /* SctBase */\
    &Mcu_SctRegister[0],      /* FAST_CR */\
    &Mcu_SctRegister[1],      /* SLOW_CR */\
    &Mcu_SctRegister[2],      /* MAIN */\
    &Mcu_SctRegister[3],      /* SUB */\
  }, \
  &Mcu_SpecialRegister,       /* SpecialBase */\
  &Mcu_Sysc0ProtKeyRegister,  /* Sysc0ProtKeyBase */\
  &Mcu_Sysc0RunRegister,      /* Sysc0RunBase */\
  &Mcu_Sysc0RunTrgRegister,   /* Sysc0RunTrgBase */\
  &Mcu_Sysc0PssRegister,      /* Sysc0PssBase */\
  &Mcu_Sysc0PssEnRegister,    /* Sysc0PssEnBase */\
  &Mcu_Sysc0AppRegister,      /* Sysc0AppBase */\
  &Mcu_Sysc0StsRegister,      /* Sysc0StsBase */\
  &Mcu_Sysc1ProtKeyRegister,  /* Sysc1ProtKeyBase */\
  &Mcu_Sysc1RunRegister,      /* Sysc1RunBase */\
  &Mcu_Sysc1RunEnRegister,    /* Sysc1RunEnBase */\
  &Mcu_Sysc1PssRegister,      /* Sysc1PssBase */\
  &Mcu_Sysc1PssEnRegister,    /* Sysc1PssEnBase */\
  &Mcu_Sysc1AppRegister,      /* Sysc1AppBase */\
  &Mcu_Sysc1StsRegister,      /* Sysc1StsBase */\
  &Mcu_FlashProtKeyRegister,  /* FlashProtKeyBase */\
  &Mcu_FlashRegister,         /* FlashBase */\
  &Mcu_WorkFlashProtKeyRegister,  /* WorkFlashProtKeyBase */\
  &Mcu_WorkFlashRegister,         /* WorkFlashBase */\
  &Mcu_ResetCntrRegister,     /* ResetCntrBase */\
  &Mcu_ResetRegister,         /* ResetBase */\
  &Mcu_SystemRegister,        /* SystemBase */\
  &Mcu_NmiRegister,           /* NmiBase */\
  &Mcu_ClockMonitorRegister,  /* ClockMonitorBase */\
  FALSE /* ScrCntrFlag */\
}

#endif

#define MCU_CLOCK_GEAR_REGISTER_MANAGE_DATA \
{ \
  { /* PLL0 */\
    MCU_SOURCE_CLOCK_PLL0, /* CgKind */\
    MCU_REG_IDX_CG_PLL0 /* CgIndex */\
  }, \
  { /* PLL1 */\
    MCU_SOURCE_CLOCK_PLL1, /* CgKind */\
    MCU_REG_IDX_CG_PLL1 /* CgIndex */\
  }, \
  { /* PLL2 */\
    MCU_SOURCE_CLOCK_PLL2, /* CgKind */\
    MCU_REG_IDX_CG_PLL2 /* CgIndex */\
  }, \
  { /* PLL3 */\
    MCU_SOURCE_CLOCK_PLL3, /* CgKind */\
    MCU_REG_IDX_CG_PLL3 /* CgIndex */\
  }, \
  { /* SSCG0 */\
    MCU_SOURCE_CLOCK_SSCG0, /* CgKind */\
    MCU_REG_IDX_CG_SSCG0 /* CgIndex */\
  }, \
  { /* SSCG1 */\
    MCU_SOURCE_CLOCK_SSCG1, /* CgKind */\
    MCU_REG_IDX_CG_SSCG1 /* CgIndex */\
  }, \
  { /* SSCG2 */\
    MCU_SOURCE_CLOCK_SSCG2, /* CgKind */\
    MCU_REG_IDX_CG_SSCG2 /* CgIndex */\
  }, \
  { /* SSCG3 */\
    MCU_SOURCE_CLOCK_SSCG3, /* CgKind */\
    MCU_REG_IDX_CG_SSCG3 /* CgIndex */\
  } \
}

#define MCU_CLOCK_SUPERVISOR_REGISTER_MANAGE_DATA \
{ \
  { /* FAST_CR */\
    MCU_CSV_CLOCK_FAST_CR, /* CsvKind */\
    MCU_REG_IDX_CSV_FAST_CR /* CsvIndex */\
  }, \
  { /* SLOW_CR */\
    MCU_CSV_CLOCK_SLOW_CR, /* CsvKind */\
    MCU_REG_IDX_CSV_SLOW_CR /* CsvIndex */\
  }, \
  { /* MAIN */\
    MCU_CSV_CLOCK_MAIN, /* CsvKind */\
    MCU_REG_IDX_CSV_MAIN /* CsvIndex */\
  }, \
  { /* SUB */\
    MCU_CSV_CLOCK_SUB, /* CsvKind */\
    MCU_REG_IDX_CSV_SUB /* CsvIndex */\
  }, \
  { /* PLL0 */\
    MCU_CSV_CLOCK_PLL0, /* CsvKind */\
    MCU_REG_IDX_CSV_PLL0 /* CsvIndex */\
  }, \
  { /* PLL1 */\
    MCU_CSV_CLOCK_PLL1, /* CsvKind */\
    MCU_REG_IDX_CSV_PLL1 /* CsvIndex */\
  }, \
  { /* PLL2 */\
    MCU_CSV_CLOCK_PLL2, /* CsvKind */\
    MCU_REG_IDX_CSV_PLL2 /* CsvIndex */\
  }, \
  { /* PLL3 */\
    MCU_CSV_CLOCK_PLL3, /* CsvKind */\
    MCU_REG_IDX_CSV_PLL3 /* CsvIndex */\
  }, \
  { /* SSCG0 */\
    MCU_CSV_CLOCK_SSCG0, /* CsvKind */\
    MCU_REG_IDX_CSV_SSCG0 /* CsvIndex */\
  }, \
  { /* SSCG1 */\
    MCU_CSV_CLOCK_SSCG1, /* CsvKind */\
    MCU_REG_IDX_CSV_SSCG1 /* CsvIndex */\
  }, \
  { /* SSCG2 */\
    MCU_CSV_CLOCK_SSCG2, /* CsvKind */\
    MCU_REG_IDX_CSV_SSCG2 /* CsvIndex */\
  }, \
  { /* SSCG3 */\
    MCU_CSV_CLOCK_SSCG3, /* CsvKind */\
    MCU_REG_IDX_CSV_SSCG3 /* CsvIndex */\
  } \
}

#define MCU_PROFILE_PLL_REGISTER_MANAGE_DATA \
{ \
  { /* PLL0 */\
    MCU_SOURCE_CLOCK_PLL0, /* PllKind */\
    MCU_REG_IDX_PLL_PLL0 /* PllIndex */\
  }, \
  { /* PLL1 */\
    MCU_SOURCE_CLOCK_PLL1, /* PllKind */\
    MCU_REG_IDX_PLL_PLL1 /* PllIndex */\
  }, \
  { /* PLL2 */\
    MCU_SOURCE_CLOCK_PLL2, /* PllKind */\
    MCU_REG_IDX_PLL_PLL2 /* PllIndex */\
  }, \
  { /* PLL3 */\
    MCU_SOURCE_CLOCK_PLL3, /* PllKind */\
    MCU_REG_IDX_PLL_PLL3 /* PllIndex */\
  } \
}

#define MCU_PROFILE_SSCG_REGISTER_MANAGE_DATA \
{ \
  { /* SSCG0 */\
    MCU_SOURCE_CLOCK_SSCG0, /* SscgKind */\
    MCU_REG_IDX_SSCG_SSCG0, /* SscgIndex */\
  }, \
  { /* SSCG1 */\
    MCU_SOURCE_CLOCK_SSCG1, /* SscgKind */\
    MCU_REG_IDX_SSCG_SSCG1, /* SscgIndex */\
  }, \
  { /* SSCG2 */\
    MCU_SOURCE_CLOCK_SSCG2, /* SscgKind */\
    MCU_REG_IDX_SSCG_SSCG2, /* SscgIndex */\
  }, \
  { /* SSCG3 */\
    MCU_SOURCE_CLOCK_SSCG3, /* SscgKind */\
    MCU_REG_IDX_SSCG_SSCG3, /* SscgIndex */\
  } \
}

#define MCU_DRIVER_CONFIG_DATA \
{ \
  (0x0U | MCU_FLAGS_INIT_CLOCK | MCU_FLAGS_HOLD_CONTROL | MCU_FLAGS_CLEAR_RESET_REASON),          /* ConfigFlags    */\
  FALSE, /* ClockFailure   */\
  1U,       /* RamConfigNum */\
  TRUE,             /* ResetConfigNum */\
  3U,     /* ModeConfigNum */\
  3U,    /* ClockConfigNum */\
  McuConf_McuClockSettingConfig_McuClockSettingConfig_RUN,       /* DefaultClockSettingId */\
  &Mcu_RamConfigData[0],         /* RamConfigPtr */\
  {MCU_REG_RESET_TYPE_SWHRST},                /* ResetConfig  */\
  &Mcu_ModeConfigData[0],          /* ModeConfigPtr */\
  &Mcu_ClockConfigData[0],         /* ClockConfigPtr */\
  { /* NotificationSet */\
    (Mcu_NotifyFctType)NULL_PTR,         /* IntLvdNotification */\
    (Mcu_NotifyFctType)NULL_PTR,       /* IntExLvdNotification */\
    (Mcu_NotifyFctType)NULL_PTR,         /* ExtLvdNotification */\
    (Mcu_NotifyFctType)NULL_PTR,       /* ExtExLvdNotification */\
    (Mcu_NotifyFctType)NULL_PTR,         /* FcrCsvNotification */\
    (Mcu_NotifyFctType)NULL_PTR,         /* ScrCsvNotification */\
    (Mcu_NotifyFctType)NULL_PTR,        /* MainCsvNotification */\
    (Mcu_NotifyFctType)NULL_PTR,         /* SubCsvNotification */\
    (Mcu_NotifyFctType)NULL_PTR,        /* Pll0CsvNotification */\
    (Mcu_NotifyFctType)NULL_PTR,        /* Pll1CsvNotification */\
    (Mcu_NotifyFctType)NULL_PTR,        /* Pll2CsvNotification */\
    (Mcu_NotifyFctType)NULL_PTR,        /* Pll3CsvNotification */\
    (Mcu_NotifyFctType)NULL_PTR,       /* Sscg0CsvNotification */\
    (Mcu_NotifyFctType)NULL_PTR,       /* Sscg1CsvNotification */\
    (Mcu_NotifyFctType)NULL_PTR,       /* Sscg2CsvNotification */\
    (Mcu_NotifyFctType)NULL_PTR,       /* Sscg3CsvNotification */\
    (Mcu_NotifyFctType)NULL_PTR,        /* MainAmpCsvNotification */\
    (Mcu_NotifyFctType)NULL_PTR,        /* SubAmpCsvNotification */\
  	(Mcu_NotifyFctType)NULL_PTR,        /* ExPll0CsvNotification */\
    (Mcu_NotifyFctType)NULL_PTR,        /* ExPll1CsvNotification */\
    (Mcu_NotifyFctType)NULL_PTR,        /* ExPll2CsvNotification */\
  }, \
  0U,     /* ClockGearWaitCount */\
  0U,     /* RunUpdateWaitCount */\
  0U,     /* ExPllClockWaitCount */\
  0U,     /* ExPllClockRestoreWaitCount */\
  9500300U   /* RunUpdateWaitCountDef */\
}

/*==================[type definitions]=======================================*/
/*==================[external function declarations]=========================*/
/*==================[internal function declarations]=========================*/
/*==================[external constants]=====================================*/
/*==================[internal constants]=====================================*/
/*==================[external data]==========================================*/
/*==================[internal data]==========================================*/
/*==================[external function definitions]==========================*/
/*==================[internal function definitions]==========================*/


# endif /* if !defined( MCU_CFG_ARCH_H ) */
/*==================[end of file]============================================*/
