#ifndef MCU_CFG_H
#define MCU_CFG_H 1

/** \brief AUTOSAR MCU Driver
 **
 ** This file contains API definitions of the configuration of the AUTOSAR module MCU that is
 ** target independent.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL40-DRV
 **
 ** (c) 2014-2017, Cypress Semiconductor Corporation. All rights reserved.
 **
 ** Warranty and Disclaimer
 **
 ** This software product is property of Cypress Semiconductor Corporation or
 ** its subsidiaries.
 ** Any use and/or distribution rights for this software product are provided
 ** only under the Cypress Software License Agreement.
 ** Any use and/or distribution of this software product not in accordance with
 ** the terms of the Cypress Software License Agreement are unauthorized and
 ** shall constitute an infringement of Cypress intellectual property rights.
*/


/*==================[inclusions]=============================================*/

#include <TSAutosar.h>         /* Cypress specific standard types */
#include <Std_Types.h>         /* AUTOSAR standard types */
#include <Os.h>
#include <Mcu_Cfg_Arch.h>         /* AUTOSAR standard types */
#include <ErrorCalloutHandler.h>

/*==================[macros]=================================================*/
/* PRQA S 857 EOF *//* Reason for disabling: Because the number of registers is large, more than 1024 macro is necessary. */



/* Get version informations for versioning checks */
#define MCU_GEN_MODULE_ID           101U
#define MCU_GEN_VENDOR_ID           66U
#define MCU_GEN_AR_RELEASE_MAJOR_VERSION    4U
#define MCU_GEN_AR_RELEASE_MINOR_VERSION    0U
#define MCU_GEN_AR_RELEASE_REVISION_VERSION    3U
#define MCU_GEN_SW_MAJOR_VERSION    1U
#define MCU_GEN_SW_MINOR_VERSION    0U
#define MCU_GEN_SW_PATCH_VERSION    29U

/* Generate dem switch settings */
#define MCU_DEM_E_SWITCH STD_OFF

#if (MCU_DEM_E_SWITCH == STD_ON)
#define MCU_E_CLOCK_FAILURE_ERROR   0U
#endif

/* Generate symbolic names for the different clock settings */
#define McuConf_McuClockSettingConfig_McuClockSettingConfig_PSS  2U
#define McuConf_McuClockSettingConfig_McuClockSettingConfig_RUN  1U
#define McuConf_McuClockSettingConfig_McuClockSettingConfig_RUN_RTC  3U
  
/* Generate symbolic names for the different ram sector settings */
#define McuConf_McuRamSectorSettingConf_McuRamSectorSettingConf_RUN  0U

/* Generate symbolic names for the different mode settings */
#define McuConf_McuModeSettingConf_McuModeSettingConf_RUN_RTC  3U
#define McuConf_McuModeSettingConf_McuModeSettingConf_PSS  2U
#define McuConf_McuModeSettingConf_McuModeSettingConf_RUN  1U

/* Generate symbolic names for the different clock reference point settings */
#define MCU_McuClockSettingConfig_PSS_McuClockReferencePoint_PSS_HPM_MCU_RUN_CLK_HPM 4000000.0F
#define MCU_McuClockSettingConfig_PSS_McuClockReferencePoint_PSS_LCP0A_MCU_RUN_CLK_LCP0A 4000000.0F
#define MCU_McuClockSettingConfig_PSS_McuClockReferencePoint_PSS_MAIN_MCU_CLK_MAIN 8000000.0F
#define MCU_McuClockSettingConfig_PSS_McuClockReferencePoint_PSS_PLL0_MCU_RUN_CLK_PLL0 0.0F
#define MCU_McuClockSettingConfig_RUN_McuClockReferencePoint_HPM_MCU_RUN_CLK_HPM 120000000.0F
#define MCU_McuClockSettingConfig_RUN_McuClockReferencePoint_LCP0A_MCU_RUN_CLK_LCP0A 60000000.0F
#define MCU_McuClockSettingConfig_RUN_McuClockReferencePoint_LCP1A_MCU_RUN_CLK_LCP1A 60000000.0F
#define MCU_McuClockSettingConfig_RUN_McuClockReferencePoint_LLPBM2_MCU_RUN_CLK_LLPBM2 120000000.0F
#define MCU_McuClockSettingConfig_RUN_McuClockReferencePoint_MAIN_MCU_CLK_MAIN 8000000.0F
#define MCU_McuClockSettingConfig_RUN_McuClockReferencePoint_PLL0_MCU_RUN_CLK_PLL0 240000000.0F
#define MCU_McuClockSettingConfig_RUN_McuClockReferencePoint_LCP_MCU_RUN_CLK_LCP 60000000.0F
#define MCU_McuClockSettingConfig_RUN_McuClockReferencePoint_COMH_MCU_RUN_CLK_COMH 58000000.0F
#define MCU_McuClockSettingConfig_RUN_McuClockReferencePoint_COMP_MCU_RUN_CLK_COMP 58000000.0F
#define MCU_McuClockSettingConfig_RUN_McuClockReferencePoint_PLLOUT0_MCU_RUN_CLK_PLLOUT0 480000000.0F
#define MCU_McuClockSettingConfig_RUN_RTC_McuClockReferencePoint_HPM_MCU_RUN_CLK_HPM 120000000.0F
#define MCU_McuClockSettingConfig_RUN_RTC_McuClockReferencePoint_LCP0A_MCU_RUN_CLK_LCP0A 60000000.0F
#define MCU_McuClockSettingConfig_RUN_RTC_McuClockReferencePoint_LCP1A_MCU_RUN_CLK_LCP1A 60000000.0F
#define MCU_McuClockSettingConfig_RUN_RTC_McuClockReferencePoint_LLPBM2_MCU_RUN_CLK_LLPBM2 120000000.0F
#define MCU_McuClockSettingConfig_RUN_RTC_McuClockReferencePoint_MAIN_MCU_CLK_MAIN 8000000.0F
#define MCU_McuClockSettingConfig_RUN_RTC_McuClockReferencePoint_PLL0_MCU_RUN_CLK_PLL0 240000000.0F
#define MCU_McuClockSettingConfig_RUN_RTC_McuClockReferencePoint_LCP_MCU_RUN_CLK_LCP 60000000.0F
#define MCU_McuClockSettingConfig_RUN_RTC_McuClockReferencePoint_COMH_MCU_RUN_CLK_COMH 58000000.0F
#define MCU_McuClockSettingConfig_RUN_RTC_McuClockReferencePoint_COMP_MCU_RUN_CLK_COMP 58000000.0F


/* Generate symbolic names for the different reset reason settings */
#define McuConf_McuResetReasonConf_MCU_RESET_UNDEFINED  0U
#define McuConf_McuResetReasonConf_MCU_POWER_ON_RESET  1U
#define McuConf_McuResetReasonConf_MCU_LOW_VOLTAGE_RAM_RETAIN_RESET  2U
#define McuConf_McuResetReasonConf_MCU_INITX_RESET  3U
#define McuConf_McuResetReasonConf_MCU_ILLEGAL_MODE_RESET  4U
#define McuConf_McuResetReasonConf_MCU_EXTERNAL_RESET  5U
#define McuConf_McuResetReasonConf_MCU_LOW_VOLTAGE_INTERNAL_RESET  6U
#define McuConf_McuResetReasonConf_MCU_LOW_VOLTAGE_INTERNAL_EXTRA_RESET  7U
#define McuConf_McuResetReasonConf_MCU_LOW_VOLTAGE_EXTERNAL_RESET  8U
#define McuConf_McuResetReasonConf_MCU_LOW_VOLTAGE_EXTERNAL_EXTRA_RESET  9U
#define McuConf_McuResetReasonConf_MCU_CLOCK_STOP_WAIT_RESET  10U
#define McuConf_McuResetReasonConf_MCU_SRSTX_RESET  11U
#define McuConf_McuResetReasonConf_MCU_PROFILE_ERROR_RESET  12U
#define McuConf_McuResetReasonConf_MCU_WATCHDOG_RESET  13U
#define McuConf_McuResetReasonConf_MCU_WATCHDOG_SW_RESET  14U
#define McuConf_McuResetReasonConf_MCU_SW_RESET  15U
#define McuConf_McuResetReasonConf_MCU_SW_TRIGGER_HW_RESET  16U
#define McuConf_McuResetReasonConf_MCU_SLOW_CR_CLOCK_STOP_RESET  17U
#define McuConf_McuResetReasonConf_MCU_FAST_CR_CLOCK_STOP_RESET  18U
#define McuConf_McuResetReasonConf_MCU_MAIN_CLOCK_STOP_RESET  19U
#define McuConf_McuResetReasonConf_MCU_SUB_CLOCK_STOP_RESET  20U
#define McuConf_McuResetReasonConf_MCU_PLL0_STOP_RESET  21U
#define McuConf_McuResetReasonConf_MCU_PLL1_STOP_RESET  22U
#define McuConf_McuResetReasonConf_MCU_PLL2_STOP_RESET  23U
#define McuConf_McuResetReasonConf_MCU_PLL3_STOP_RESET  24U
#define McuConf_McuResetReasonConf_MCU_SSCG0_STOP_RESET  25U
#define McuConf_McuResetReasonConf_MCU_SSCG1_STOP_RESET  26U
#define McuConf_McuResetReasonConf_MCU_SSCG2_STOP_RESET  27U
#define McuConf_McuResetReasonConf_MCU_SSCG3_STOP_RESET  28U
#define McuConf_McuResetReasonConf_MCU_WAKEUP_RESET  29U

/* Generate macro for the clock initialization */
#define MCU_INIT_CLOCK STD_ON

/* Generate macro for whether H/W has PLL circuit. */
#define MCU_NO_PLL STD_OFF

/* Generate macro for whether H/W has expand PLL circuit. */
#define MCU_NO_EXPLL STD_ON

/* Generate macro for enable or disable the function Mcu_PerformReset(). */
#define MCU_PERFORM_RESET_API STD_ON

/* Generate macro for enable or disable the function Mcu_GetVersionInfo(). */
#define MCU_VERSION_INFO_API STD_ON

/* Generate macro for enable or disable the default clock setting. */
#define MCU_ENABLE_DEFAULT_CLOCK STD_ON

/* Generate macro for enable or disable the development error detection and reporting. */
#define MCU_DEV_ERROR_DETECT STD_ON

/* Generate macro for enable or disable the safety function. */
#define MCU_SAFETY_FUNCTION_API STD_ON

/* Generate macro for enable or disable the control of output hold. */
#define MCU_ENABLE_HOLD_CONTROL STD_ON

/* Generate macro for enable or disable the recover register. */
#define MCU_ENABLE_RECOVER_REGISTER STD_ON

/* Generate macro for enable or disable the clock gear function. */
#define MCU_CLOCK_GEAR_API STD_ON

/* Generate macro for enable or disable the function Mcu_SetIoResetControl(). */
#define MCU_IO_RESET_CONTROL_API STD_OFF


/* This parameter defines the existence and the name of a callout function that is 
   called each time an error was detected.
   The function has to have the following parameters: (ModuleId: uint16,
   InstanceId: uint8, ApiId: uint8, ErrorId: uint8) */
#define MCU_ERROR_CALLOUT_FUNCTION ErrorCalloutHandler

/*==================[type definitions]=======================================*/
/*==================[external function declarations]=========================*/
/*==================[internal function declarations]=========================*/
/*==================[external constants]=====================================*/
/*==================[internal constants]=====================================*/
/*==================[external data]==========================================*/
/*==================[internal data]==========================================*/
/*==================[external function definitions]==========================*/
/*==================[internal function definitions]==========================*/


# endif /* if !defined( MCU_CFG_H ) */
/*==================[end of file]============================================*/
