#ifndef PORT_CFG_H
#define PORT_CFG_H

/** \brief AUTOSAR Port Port Driver
 **
 ** This file contains API definitions of the configuration of the
 ** AUTOSAR module Port that is target independent.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL40-DRV
 **
 ** (c) 2014-2017, Cypress Semiconductor Corporation. All rights reserved.
 **
 ** Warranty and Disclaimer
 **
 ** This software product is property of Cypress Semiconductor Corporation or
 ** its subsidiaries.
 ** Any use and/or distribution rights for this software product are provided
 ** only under the Cypress Software License Agreement.
 ** Any use and/or distribution of this software product not in accordance with
 ** the terms of the Cypress Software License Agreement are unauthorized and
 ** shall constitute an infringement of Cypress intellectual property rights.
*/
/*==================[inclusions]=============================================*/
#include <ErrorCalloutHandler.h>
#include <Port_Cfg_Der.h>     /* include architecture specific configuration part */

/*==================[macros]=================================================*/
#define PORT_GEN_MODULE_ID                   124U  /* Module ID */
#define PORT_GEN_VENDOR_ID                   66U   /* Vendor ID */
#define PORT_GEN_AR_RELEASE_MAJOR_VERSION    4U    /* Autosar Release Major Version */
#define PORT_GEN_AR_RELEASE_MINOR_VERSION    0U    /* Autosar Release Minor Version */
#define PORT_GEN_AR_RELEASE_REVISION_VERSION 3U    /* Autosar Release Revision Version */
#define PORT_GEN_SW_MAJOR_VERSION            1U    /* Software Major Version */
#define PORT_GEN_SW_MINOR_VERSION            0U    /* Software Minor Version */
#define PORT_GEN_SW_PATCH_VERSION            29U    /* Software Patch Version */

/* Symbolic names for user configured Port Pins */
  /* For PortConfigSet_RUN/PortContainer_RUN */
#define PortConf_PortPin_Unused_P5_21    PORT_PIN_P521
#define PortConf_PortPin_Unused_P0_18    PORT_PIN_P018
#define PortConf_PortPin_Unused_P0_19    PORT_PIN_P019
#define PortConf_PortPin_PWM_Backlight_TACHO    PORT_PIN_P527
#define PortConf_PortPin_PWM_Backlight_SPEEDO    PORT_PIN_P528
#define PortConf_PortPin_Unused_P5_29    PORT_PIN_P529
#define PortConf_PortPin_Unused_P5_30    PORT_PIN_P530
#define PortConf_PortPin_Unused_P5_31    PORT_PIN_P531
#define PortConf_PortPin_Unused_P6_00    PORT_PIN_P600
#define PortConf_PortPin_Unused_P0_00    PORT_PIN_P000
#define PortConf_PortPin_Unused_P0_01    PORT_PIN_P001
#define PortConf_PortPin_Unused_P0_02    PORT_PIN_P002
#define PortConf_PortPin_Unused_P0_03    PORT_PIN_P003
#define PortConf_PortPin_M_CK    PORT_PIN_P004
#define PortConf_PortPin_M_DQ3    PORT_PIN_P005
#define PortConf_PortPin_M_DQ2    PORT_PIN_P006
#define PortConf_PortPin_M_DQ1    PORT_PIN_P007
#define PortConf_PortPin_M_DQ0    PORT_PIN_P008
#define PortConf_PortPin_M_CS_1    PORT_PIN_P009
#define PortConf_PortPin_M_RWDS    PORT_PIN_P010
#define PortConf_PortPin_Unused_P0_11    PORT_PIN_P011
#define PortConf_PortPin_M_DQ4    PORT_PIN_P012
#define PortConf_PortPin_M_DQ5    PORT_PIN_P013
#define PortConf_PortPin_M_DQ6    PORT_PIN_P014
#define PortConf_PortPin_M_DQ7    PORT_PIN_P015
#define PortConf_PortPin_TFT_RESET    PORT_PIN_P016
#define PortConf_PortPin_Unused_P0_17    PORT_PIN_P017
#define PortConf_PortPin_Unused_P5_22    PORT_PIN_P522
#define PortConf_PortPin_RAM_CK    PORT_PIN_P109
#define PortConf_PortPin_RAM_DQ3    PORT_PIN_P105
#define PortConf_PortPin_RAM_DQ2    PORT_PIN_P107
#define PortConf_PortPin_RAM_DQ1    PORT_PIN_P106
#define PortConf_PortPin_RAM_DQ0    PORT_PIN_P104
#define PortConf_PortPin_RAM_CS1    PORT_PIN_P108
#define PortConf_PortPin_RAM_RWDS    PORT_PIN_P030
#define PortConf_PortPin_Unused_P0_31    PORT_PIN_P031
#define PortConf_PortPin_RAM_DQ4    PORT_PIN_P101
#define PortConf_PortPin_RAM_DQ5    PORT_PIN_P100
#define PortConf_PortPin_RAM_DQ6    PORT_PIN_P103
#define PortConf_PortPin_RAM_DQ7    PORT_PIN_P102
#define PortConf_PortPin_RESET_CON    PORT_PIN_P026
#define PortConf_PortPin_SHUT_DOWN    PORT_PIN_P027
#define PortConf_PortPin_Unused_P0_28    PORT_PIN_P028
#define PortConf_PortPin_P_3V3SW_EN    PORT_PIN_P222
#define PortConf_PortPin_MDI_IGN_INT    PORT_PIN_P224
#define PortConf_PortPin_MDO_SHIFT_SER_IN    PORT_PIN_P225
#define PortConf_PortPin_MDO_SHIFT_SRCK    PORT_PIN_P226
#define PortConf_PortPin_MDO_SHIFT_BAR_EN    PORT_PIN_P227
#define PortConf_PortPin_MDO_SHIFT_Telltale_EN    PORT_PIN_P228
#define PortConf_PortPin_Unused_P2_29    PORT_PIN_P229
#define PortConf_PortPin_MAI_BAT    PORT_PIN_P230
#define PortConf_PortPin_FUEL_RED    PORT_PIN_P231
#define PortConf_PortPin_EE_SDA    PORT_PIN_P300
#define PortConf_PortPin_EE_SCL    PORT_PIN_P301
#define PortConf_PortPin_MAI_Backlight_Level_uC    PORT_PIN_P302
#define PortConf_PortPin_B_CAN_MCU_STB    PORT_PIN_P303
#define PortConf_PortPin_Unused_P3_04    PORT_PIN_P304
#define PortConf_PortPin_B_CAN_MCU_RXD    PORT_PIN_P305
#define PortConf_PortPin_B_CAN_MCU_TXD    PORT_PIN_P306
#define PortConf_PortPin_Unused_P3_18    PORT_PIN_P318
#define PortConf_PortPin_Unused_P3_19    PORT_PIN_P319
#define PortConf_PortPin_Unused_P3_20    PORT_PIN_P320
#define PortConf_PortPin_PWM_Speed_Out_Uc    PORT_PIN_P321
#define PortConf_PortPin_Unused_P3_22    PORT_PIN_P322
#define PortConf_PortPin_MAI_Fuel    PORT_PIN_P323
#define PortConf_PortPin_MAI_Air_Pressure1_uC    PORT_PIN_P324
#define PortConf_PortPin_MAI_Air_Pressure2_uC    PORT_PIN_P325
#define PortConf_PortPin_RT_CLK    PORT_PIN_P326
#define PortConf_PortPin_MAI_P_BAT_C    PORT_PIN_P327
#define PortConf_PortPin_MAI_P_BAT_C_1    PORT_PIN_P328
#define PortConf_PortPin_MDI_LOCK_uC    PORT_PIN_P329
#define PortConf_PortPin_DO_TCU_D_Uc    PORT_PIN_P330
#define PortConf_PortPin_Unused_P3_31    PORT_PIN_P331
#define PortConf_PortPin_MDI_CHARGE_uC    PORT_PIN_P400
#define PortConf_PortPin_PWM_LEFT_SINP    PORT_PIN_P401
#define PortConf_PortPin_PWM_LEFT_SINN    PORT_PIN_P402
#define PortConf_PortPin_PWM_LEFT_COSP    PORT_PIN_P403
#define PortConf_PortPin_PWM_LEFT_COSN    PORT_PIN_P404
#define PortConf_PortPin_P_5VSW_EN    PORT_PIN_P405
#define PortConf_PortPin_MDO_SHIFT_RCK    PORT_PIN_P406
#define PortConf_PortPin_MDIL_Exhaust_Brake_uC    PORT_PIN_P407
#define PortConf_PortPin_Unused_P4_08    PORT_PIN_P408
#define PortConf_PortPin_PWM_RIGHT_SINP    PORT_PIN_P409
#define PortConf_PortPin_PWM_RIGHT_SINN    PORT_PIN_P410
#define PortConf_PortPin_PWM_RIGHT_COSP    PORT_PIN_P411
#define PortConf_PortPin_PWM_RIGHT_COSN    PORT_PIN_P412
#define PortConf_PortPin_MDI_Low_OilPressure_uC    PORT_PIN_P219
#define PortConf_PortPin_Unused_P3_07    PORT_PIN_P307
#define PortConf_PortPin_MDI_4W_L    PORT_PIN_P308
#define PortConf_PortPin_TFT_THERMISTOR    PORT_PIN_P309
#define PortConf_PortPin_MDI_Low_Air_Pressure_uC    PORT_PIN_P310
#define PortConf_PortPin_MDI_ParkBrake_Uc    PORT_PIN_P311
#define PortConf_PortPin_MDI_Driver_SeatBelt    PORT_PIN_P312
#define PortConf_PortPin_MDI_Passenger_SeatBelt    PORT_PIN_P313
#define PortConf_PortPin_MDI_AIRBAG_uC    PORT_PIN_P314
#define PortConf_PortPin_P_CAN_MCU_STB    PORT_PIN_P315
#define PortConf_PortPin_P_CAN_MCU_RXD    PORT_PIN_P316
#define PortConf_PortPin_P_CAN_MCU_TXD    PORT_PIN_P317
#define PortConf_PortPin_Unused_P2_17    PORT_PIN_P217
#define PortConf_PortPin_Unused_P2_16    PORT_PIN_P216
#define PortConf_PortPin_Unused_P4_29    PORT_PIN_P429
#define PortConf_PortPin_MDO_P12V_EN    PORT_PIN_P430
#define PortConf_PortPin_DISP_PWR_EN    PORT_PIN_P431
#define PortConf_PortPin_MDO_TFT_BL1_PWM    PORT_PIN_P500
#define PortConf_PortPin_MDI_TFT_BL1_FAULT    PORT_PIN_P501
#define PortConf_PortPin_MDO_TFT_BL1_EN    PORT_PIN_P502
#define PortConf_PortPin_TEST_2    PORT_PIN_P503
#define PortConf_PortPin_TEST_1    PORT_PIN_P504
#define PortConf_PortPin_Unused_P5_05    PORT_PIN_P505
#define PortConf_PortPin_Unused_P5_06    PORT_PIN_P506
#define PortConf_PortPin_Unused_P5_07    PORT_PIN_P507
#define PortConf_PortPin_Unused_P5_08    PORT_PIN_P508
#define PortConf_PortPin_Unused_P5_09    PORT_PIN_P509
#define PortConf_PortPin_Unused_P5_10    PORT_PIN_P510
#define PortConf_PortPin_Unused_P5_11    PORT_PIN_P511
#define PortConf_PortPin_Unused_P5_12    PORT_PIN_P512
#define PortConf_PortPin_Unused_P5_13    PORT_PIN_P513
#define PortConf_PortPin_Unused_P5_14    PORT_PIN_P514
#define PortConf_PortPin_MDO_BACKLIGHT_SCALE    PORT_PIN_P515
#define PortConf_PortPin_MDO_BACKLIGHT_Decoration    PORT_PIN_P516
#define PortConf_PortPin_MDO_BAT_C_1    PORT_PIN_P517
#define PortConf_PortPin_Unused_P5_18    PORT_PIN_P518
#define PortConf_PortPin_Unused_P5_19    PORT_PIN_P519
#define PortConf_PortPin_Unused_P5_20    PORT_PIN_P520
#define PortConf_PortPin_Unused_P4_25    PORT_PIN_P425
#define PortConf_PortPin_DSP_Standby_MODE    PORT_PIN_P426
#define PortConf_PortPin_Unused_P4_27    PORT_PIN_P427
#define PortConf_PortPin_Unused_P4_28    PORT_PIN_P428
  /* For PortConfigSet_PSS/PortContainer_0 */
#define PortConf_PortPin_PSS_Unused_P5_21    PORT_PIN_P521
#define PortConf_PortPin_PSS_Unused_P0_18    PORT_PIN_P018
#define PortConf_PortPin_PSS_Unused_P0_19    PORT_PIN_P019
#define PortConf_PortPin_PSS_Unused_P5_27    PORT_PIN_P527
#define PortConf_PortPin_PSS_Unused_P5_28    PORT_PIN_P528
#define PortConf_PortPin_PSS_Unused_P5_29    PORT_PIN_P529
#define PortConf_PortPin_PSS_Unused_P5_30    PORT_PIN_P530
#define PortConf_PortPin_PSS_Unused_P5_31    PORT_PIN_P531
#define PortConf_PortPin_PSS_Unused_P6_00    PORT_PIN_P600
#define PortConf_PortPin_PSS_Unused_P0_00    PORT_PIN_P000
#define PortConf_PortPin_PSS_Unused_P0_01    PORT_PIN_P001
#define PortConf_PortPin_PSS_Unused_P0_02    PORT_PIN_P002
#define PortConf_PortPin_PSS_Unused_P0_03    PORT_PIN_P003
#define PortConf_PortPin_PSS_M_CK    PORT_PIN_P004
#define PortConf_PortPin_PSS_M_DQ3    PORT_PIN_P005
#define PortConf_PortPin_PSS_M_DQ2    PORT_PIN_P006
#define PortConf_PortPin_PSS_M_DQ1    PORT_PIN_P007
#define PortConf_PortPin_PSS_M_DQ0    PORT_PIN_P008
#define PortConf_PortPin_PSS_M_CS_1    PORT_PIN_P009
#define PortConf_PortPin_PSS_M_RWDS    PORT_PIN_P010
#define PortConf_PortPin_PSS_Unused_P0_11    PORT_PIN_P011
#define PortConf_PortPin_PSS_M_DQ4    PORT_PIN_P012
#define PortConf_PortPin_PSS_M_DQ5    PORT_PIN_P013
#define PortConf_PortPin_PSS_M_DQ6    PORT_PIN_P014
#define PortConf_PortPin_PSS_M_DQ7    PORT_PIN_P015
#define PortConf_PortPin_PSS_TFT_RESET    PORT_PIN_P016
#define PortConf_PortPin_PSS_Unused_P0_17    PORT_PIN_P017
#define PortConf_PortPin_PSS_Unused_P5_22    PORT_PIN_P522
#define PortConf_PortPin_PSS_RAM_CK    PORT_PIN_P109
#define PortConf_PortPin_PSS_RAM_DQ3    PORT_PIN_P105
#define PortConf_PortPin_PSS_RAM_DQ2    PORT_PIN_P107
#define PortConf_PortPin_PSS_RAM_DQ1    PORT_PIN_P106
#define PortConf_PortPin_PSS_RAM_DQ0    PORT_PIN_P104
#define PortConf_PortPin_PSS_RAM_CS1    PORT_PIN_P108
#define PortConf_PortPin_PSS_RAM_RWDS    PORT_PIN_P030
#define PortConf_PortPin_PSS_Unused_P0_31    PORT_PIN_P031
#define PortConf_PortPin_PSS_RAM_DQ4    PORT_PIN_P101
#define PortConf_PortPin_PSS_RAM_DQ5    PORT_PIN_P100
#define PortConf_PortPin_PSS_RAM_DQ6    PORT_PIN_P103
#define PortConf_PortPin_PSS_RAM_DQ7    PORT_PIN_P102
#define PortConf_PortPin_PSS_RESET_CON    PORT_PIN_P026
#define PortConf_PortPin_PSS_SHUT_DOWN    PORT_PIN_P027
#define PortConf_PortPin_PSS_Unused_P0_28    PORT_PIN_P028
#define PortConf_PortPin_PSS_P_3V3SW_EN    PORT_PIN_P222
#define PortConf_PortPin_PSS_MDI_IGN_INT    PORT_PIN_P224
#define PortConf_PortPin_PSS_MDO_SHIFT_SER_IN    PORT_PIN_P225
#define PortConf_PortPin_PSS_MDO_SHIFT_SRCK    PORT_PIN_P226
#define PortConf_PortPin_PSS_MDO_SHIFT_BAR_EN    PORT_PIN_P227
#define PortConf_PortPin_PSS_MDO_SHIFT_Telltale_EN    PORT_PIN_P228
#define PortConf_PortPin_PSS_Unused_P2_29    PORT_PIN_P229
#define PortConf_PortPin_PSS_MAI_BAT    PORT_PIN_P230
#define PortConf_PortPin_PSS_Unused_P2_31    PORT_PIN_P231
#define PortConf_PortPin_PSS_EE_SDA    PORT_PIN_P300
#define PortConf_PortPin_PSS_EE_SCL    PORT_PIN_P301
#define PortConf_PortPin_PSS_MAI_Backlight_Level_uC    PORT_PIN_P302
#define PortConf_PortPin_PSS_B_CAN_MCU_STB    PORT_PIN_P303
#define PortConf_PortPin_PSS_Unused_P3_04    PORT_PIN_P304
#define PortConf_PortPin_PSS_B_CAN_MCU_RXD    PORT_PIN_P305
#define PortConf_PortPin_PSS_B_CAN_MCU_TXD    PORT_PIN_P306
#define PortConf_PortPin_PSS_Unused_P3_18    PORT_PIN_P318
#define PortConf_PortPin_PSS_Unused_P3_19    PORT_PIN_P319
#define PortConf_PortPin_PSS_Unused_P3_20    PORT_PIN_P320
#define PortConf_PortPin_PSS_PWM_Speed_Out_Uc    PORT_PIN_P321
#define PortConf_PortPin_PSS_Unused_P3_22    PORT_PIN_P322
#define PortConf_PortPin_PSS_MAI_Fuel    PORT_PIN_P323
#define PortConf_PortPin_PSS_DO_TCU_S_uC    PORT_PIN_P324
#define PortConf_PortPin_PSS_DO_TCU_N_Uc    PORT_PIN_P325
#define PortConf_PortPin_PSS_RT_CLK    PORT_PIN_P326
#define PortConf_PortPin_PSS_MAI_P_BAT_C    PORT_PIN_P327
#define PortConf_PortPin_PSS_MAI_P_BAT_C_1    PORT_PIN_P328
#define PortConf_PortPin_PSS_Unused_P3_29    PORT_PIN_P329
#define PortConf_PortPin_PSS_DO_TCU_D_Uc    PORT_PIN_P330
#define PortConf_PortPin_PSS_Unused_P3_31    PORT_PIN_P331
#define PortConf_PortPin_PSS_MDI_CHARGE_uC    PORT_PIN_P400
#define PortConf_PortPin_PSS_Unused_P4_01    PORT_PIN_P401
#define PortConf_PortPin_PSS_Unused_P4_02    PORT_PIN_P402
#define PortConf_PortPin_PSS_Unused_P4_03    PORT_PIN_P403
#define PortConf_PortPin_PSS_Unused_P4_04    PORT_PIN_P404
#define PortConf_PortPin_PSS_P_5VSW_EN    PORT_PIN_P405
#define PortConf_PortPin_PSS_MDO_SHIFT_RCK    PORT_PIN_P406
#define PortConf_PortPin_PSS_MDI_4W_H    PORT_PIN_P407
#define PortConf_PortPin_PSS_Unused_P4_08    PORT_PIN_P408
#define PortConf_PortPin_PSS_Unused_P4_09    PORT_PIN_P409
#define PortConf_PortPin_PSS_Unused_P4_10    PORT_PIN_P410
#define PortConf_PortPin_PSS_Unused_P4_11    PORT_PIN_P411
#define PortConf_PortPin_PSS_POWER_FAULT    PORT_PIN_P412
#define PortConf_PortPin_PSS_Unused_P2_19    PORT_PIN_P219
#define PortConf_PortPin_PSS_Unused_P3_07    PORT_PIN_P307
#define PortConf_PortPin_PSS_MDI_4W_L    PORT_PIN_P308
#define PortConf_PortPin_PSS_TFT_THERMISTOR    PORT_PIN_P309
#define PortConf_PortPin_PSS_MDI_Oil_Pressure_SW    PORT_PIN_P310
#define PortConf_PortPin_PSS_MDI_ParkBrake_Uc    PORT_PIN_P311
#define PortConf_PortPin_PSS_MDI_Driver_SeatBelt    PORT_PIN_P312
#define PortConf_PortPin_PSS_MDI_Passenger_SeatBelt    PORT_PIN_P313
#define PortConf_PortPin_PSS_MDI_AIRBAG_uC    PORT_PIN_P314
#define PortConf_PortPin_PSS_P_CAN_MCU_STB    PORT_PIN_P315
#define PortConf_PortPin_PSS_P_CAN_MCU_RXD    PORT_PIN_P316
#define PortConf_PortPin_PSS_P_CAN_MCU_TXD    PORT_PIN_P317
#define PortConf_PortPin_PSS_Unused_P2_17    PORT_PIN_P217
#define PortConf_PortPin_PSS_Unused_P2_16    PORT_PIN_P216
#define PortConf_PortPin_PSS_Unused_P4_29    PORT_PIN_P429
#define PortConf_PortPin_PSS_MDO_P12V_EN    PORT_PIN_P430
#define PortConf_PortPin_PSS_DISP_PWR_EN    PORT_PIN_P431
#define PortConf_PortPin_PSS_MDO_TFT_BL1_PWM    PORT_PIN_P500
#define PortConf_PortPin_PSS_MDI_TFT_BL1_FAULT    PORT_PIN_P501
#define PortConf_PortPin_PSS_MDO_TFT_BL1_EN    PORT_PIN_P502
#define PortConf_PortPin_PSS_TEST_2    PORT_PIN_P503
#define PortConf_PortPin_PSS_TEST_1    PORT_PIN_P504
#define PortConf_PortPin_PSS_Unused_P5_05    PORT_PIN_P505
#define PortConf_PortPin_PSS_Unused_P5_06    PORT_PIN_P506
#define PortConf_PortPin_PSS_Unused_P5_07    PORT_PIN_P507
#define PortConf_PortPin_PSS_Unused_P5_08    PORT_PIN_P508
#define PortConf_PortPin_PSS_Unused_P5_09    PORT_PIN_P509
#define PortConf_PortPin_PSS_Unused_P5_10    PORT_PIN_P510
#define PortConf_PortPin_PSS_Unused_P5_11    PORT_PIN_P511
#define PortConf_PortPin_PSS_Unused_P5_12    PORT_PIN_P512
#define PortConf_PortPin_PSS_Unused_P5_13    PORT_PIN_P513
#define PortConf_PortPin_PSS_Unused_P5_14    PORT_PIN_P514
#define PortConf_PortPin_PSS_MDO_BACKLIGHT_SCALE    PORT_PIN_P515
#define PortConf_PortPin_PSS_MDO_BACKLIGHT_Decoration    PORT_PIN_P516
#define PortConf_PortPin_PSS_MDO_BAT_C_1    PORT_PIN_P517
#define PortConf_PortPin_PSS_Unused_P5_18    PORT_PIN_P518
#define PortConf_PortPin_PSS_Unused_P5_19    PORT_PIN_P519
#define PortConf_PortPin_PSS_Unused_P5_20    PORT_PIN_P520
#define PortConf_PortPin_PSS_Unused_P4_25    PORT_PIN_P425
#define PortConf_PortPin_PSS_DSP_Standby_MODE    PORT_PIN_P426
#define PortConf_PortPin_PSS_Unused_P4_27    PORT_PIN_P427
#define PortConf_PortPin_PSS_Unused_P4_28    PORT_PIN_P428

/* Symbolic names for user configured resource inputs */
#define PortConf_PortResourceInput_P_CAN_MCU_RXD    PORT_RESOURCEINPUT_RX6
#define PortConf_PortResourceInput_B_CAN_MCU_RXD    PORT_RESOURCEINPUT_RX1
#define PortConf_PortResourceInput_PSS_B_CAN_MCU_RXD    PORT_RESOURCEINPUT_EINT5
#define PortConf_PortResourceInput_PSS_P_CAN_MCU_RXD    PORT_RESOURCEINPUT_EINT0
#define PortConf_PortResourceInput_PSS_MDI_IGN_INT    PORT_RESOURCEINPUT_EINT8

/* Symbolic names for PortPin Configurations */
#define PortConf_PortContainer_PortContainer_RUN    (Port_PinConfigs[0])
#define PortConf_PortContainer_PortContainer_0    (Port_PinConfigs[1])

/* PortConfigSet container short name  */
#define PortConfigSet_RUN    (Port_PinConfigs[0])
#define PortConfigSet_PSS    (Port_PinConfigs[1])

/* User configured API defines */
#define PORT_SET_PIN_DIRECTION_API        STD_ON
#define PORT_SET_PIN_MODE_API             STD_ON
#define PORT_VERSION_INFO_API             STD_ON
#define PORT_SET_RESOURCE_INPUT_MODE_API  STD_ON
#define PORT_SAFETY_FUNCTION_API  STD_ON

/* User configured DET defines */
#define PORT_DEV_ERROR_DETECT             STD_OFF

/** This parameter defines the existence and the name of a callout function that is
 called each time an error was detected.
 The function has to have the following parameters: (ModuleId: uint16,
 InstanceId: uint8, ApiId: uint8, ErrorId: uint8) */
#define PORT_ERROR_CALLOUT_FUNCTION ErrorCalloutHandler

/*==================[type definitions]=======================================*/
/*==================[external function declarations]=========================*/
/*==================[internal function declarations]=========================*/
/*==================[external constants]=====================================*/
/*==================[internal constants]=====================================*/
/*==================[external data]==========================================*/
/*==================[internal data]==========================================*/
/*==================[external function definitions]==========================*/
/*==================[internal function definitions]==========================*/

#endif /* PORT_CFG_H  */
/*==================[end of file]============================================*/
