#ifndef SPI_CFG_DER_H_INCLUDED
#define SPI_CFG_DER_H_INCLUDED

/** \brief AUTOSAR SPI Driver
 **
 ** This file contains definitions for configuration related to hardware units.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL40-DRV
 **
 ** (c) 2016-2017, Cypress Semiconductor Corporation. All rights reserved.
 **
 ** Warranty and Disclaimer
 **
 ** This software product is property of Cypress Semiconductor Corporation or
 ** its subsidiaries.
 ** Any use and/or distribution rights for this software product are provided
 ** only under the Cypress Software License Agreement.
 ** Any use and/or distribution of this software product not in accordance with
 ** the terms of the Cypress Software License Agreement are unauthorized and
 ** shall constitute an infringement of Cypress intellectual property rights.
 */

/*==================[inclusions]============================================*/
#include <Spi_Internal_Types.h>

/*==================[macros]================================================*/

/* SPI feature definitions */

/** Number of FIFO entries (determined by HW) */
#define SPI_DERIVATE_FIFO_SIZE  64U


/*  The next macros can be overridden by the integrator via command line parameter.
    Doing so is at own risk! */

/* MFS base addresses */

/** Base address of MFS00 */
#ifndef SPI_MFS00_BASE_ADDRESS
/** Base-Address of hold clear bit of interrupt control unit. */
  #define SPI_MFS00_BASE_ADDRESS  0xb4800000U
#else
  /* Deviation from MISRA-C:2004 Rule 19.16:
     Unrecognized preprocessing directive has been ignored because of conditional inclusion directives.
     Justification: The preprocessing directive is a warning that indicates a special build 
     configuration which is not suitable for production software. */
  /* PRQA S 3115 1 */
  #warning SPI_MFS00_BASE_ADDRESS is overridden by the environment. This is not intended for production software!
#endif


/* DMA base addresses */




/* Client interface base addresses */



/*------------------[other HW dependent configuration]------------------ */

#define SPI_MFSI_REGS \
{ \
  (P2VAR(Spi_MFSIRegsType, SPI_CONST, SPI_APPL_DATA)) SPI_MFS00_BASE_ADDRESS \
}


#define SPI_DMA_RX_CHANNEL_REGS \
{ \
  (P2VAR(Spi_DmaChannelRegsType, SPI_CONST, SPI_APPL_DATA))NULL_PTR /* no DMA for MFS00 */ \
}

#define SPI_DMA_TX_CHANNEL_REGS \
{ \
  (P2VAR(Spi_DmaChannelRegsType, SPI_CONST, SPI_APPL_DATA))NULL_PTR /* no DMA for MFS00 */ \
}

#define SPI_DMA_RX_CHANNEL_CLIENT_INTERFACE_REGS \
{ \
  (P2VAR(Spi_DmaChannelClientInterfaceRegType, SPI_CONST, SPI_APPL_DATA))NULL_PTR /* no DMA for MFS00 */ \
}

#define SPI_DMA_TX_CHANNEL_CLIENT_INTERFACE_REGS \
{ \
  (P2VAR(Spi_DmaChannelClientInterfaceRegType, SPI_CONST, SPI_APPL_DATA))NULL_PTR /* no DMA for MFS00 */ \
}

#define SPI_DMA_REQUEST_NUMBERS_RX \
{ \
  0U /* no DMA for MFS00 */ \
}

#define SPI_DMA_REQUEST_NUMBERS_TX \
{ \
  0U /* no DMA for MFS00 */ \
}



#define SPI_DMA_INTERNAL_CLIENT_INTERFACE_REG_BASE  0xb4702020U

#define SPI_DMAGLOBALREG_ADDR 0xb4701000U


#define SPI_DMAVALIDDATA_MASK 0x0U

/*==================[type definitions]======================================*/

/*==================[external function declarations]========================*/
/*==================[external constants]====================================*/

/*==================[external data]=========================================*/

/*==================[external function definitions]=========================*/

#endif /* if !defined( SPI_CFG_DER_H_INCLUDED ) */
/*==================[end of file]===========================================*/
