/** \brief Adc_Irq.c
 **
 ** Class Adc_Irq
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL40-DRV
 **
 ** (c) 2014-2017, Cypress Semiconductor Corporation. All rights reserved.
 **
 ** Warranty and Disclaimer
 **
 ** This software product is property of Cypress Semiconductor Corporation or
 ** its subsidiaries.
 ** Any use and/or distribution rights for this software product are provided
 ** only under the Cypress Software License Agreement.
 ** Any use and/or distribution of this software product not in accordance with
 ** the terms of the Cypress Software License Agreement are unauthorized and
 ** shall constitute an infringement of Cypress intellectual property rights.
 */

/*==================[inclusions]============================================*/

#include <Adc_Stream.h>
#include <Adc_Irq.h>

/*==================[macros]================================================*/

/** Pointer to the IRC IRQ hold clear register.
    
    The macro can be overridden by the integrator via command line parameter.
    Doing so is at own risk! */
#ifndef ADC_IRC0IRQHC
  #define ADC_IRC0IRQHC (*((volatile uint32*)0xB0400C48UL))
#else
  /* Deviation from MISRA-C:2004 Rule 19.16:
     Unrecognized preprocessing directive has been ignored because of conditional inclusion directives.
     Justification: The preprocessing directive is a warning that indicates a special build 
     configuration which is not suitable for production software. */
  /* PRQA S 3115 1 */
  #warning ADC_IRC0IRQHC is overridden by the environment. This is not intended for production software!
#endif

/*==================[type definitions]======================================*/

/*==================[external function declarations]========================*/

/*==================[internal function declarations]========================*/

/*==================[internal constants]====================================*/

/*==================[internal data]=========================================*/

/*==================[external function definitions]=========================*/

#define ADC_START_SEC_CODE
/* MISRA-C:2004 Rule 19.1 deviation: MemMap.h must be included in-line. */ /* PRQA S 5087 1 */
#include "MemMap.h"


/* ===== Interrupt service routines for HwUnit0 ===== */

/** \brief Adc_IsrConversionDone_HwUnit0_Cat1
 **
 ** This function is a native ISR (Cat1).
 ** It shall be started when a conversion done interrupt occurs.
 **
 */
ISR_NATIVE(Adc_IsrConversionDone_HwUnit0_Cat1)
{
  Adc_IsrGroupConversionFinished(0U);
  
  /* Reset interrupt controller hold bit. */
  /* Deviation of MISRA-C:2004 Rules 3.1, 11.3; REFERENCE - ISO:C90-6.3.4 Cast Operators - Semantics:
     Cast between a pointer to volatile object and an integral type.
     Justification: The hardware registers have absolute addresses, the cast cannot be avoided. */
  /* PRQA S 0303 1 */
  ADC_IRC0IRQHC = 353U;
}

/** \brief Adc_IsrConversionDone_HwUnit0_Cat2
 **
 ** This function is a normal function called from interrupt context (Cat2).
 ** It shall be started when a conversion done interrupt occurs.
 **
 */
ISR(Adc_IsrConversionDone_HwUnit0_Cat2)
{
  Adc_IsrGroupConversionFinished(0U);
}

/** \brief Adc_IsrRangeHit_HwUnit0_Cat1
 **
 ** This function is a native ISR (Cat1).
 ** It shall be started when a range hit interrupt occurs.
 **
 */
ISR_NATIVE(Adc_IsrRangeHit_HwUnit0_Cat1)
{
  Adc_IsrGroupConversionFinished(0U);
  
  /* Reset interrupt controller hold bit. */
  /* Deviation of MISRA-C:2004 Rules 3.1, 11.3; REFERENCE - ISO:C90-6.3.4 Cast Operators - Semantics:
     Cast between a pointer to volatile object and an integral type.
     Justification: The hardware registers have absolute addresses, the cast cannot be avoided. */
  /* PRQA S 0303 1 */
  ADC_IRC0IRQHC = 356U;
}

/** \brief Adc_IsrRangeHit_HwUnit0_Cat2
 **
 ** This function is a normal function called from interrupt context (Cat2).
 ** It shall be started when a range hit interrupt occurs.
 **
 */
ISR(Adc_IsrRangeHit_HwUnit0_Cat2)
{
  Adc_IsrGroupConversionFinished(0U);
}


#define ADC_STOP_SEC_CODE
/* MISRA-C:2004 Rule 19.1 deviation: MemMap.h must be included in-line. */ /* PRQA S 5087 1 */
#include "MemMap.h"

/*==================[internal function definitions]=========================*/

/*==================[end of file]===========================================*/
