/** \brief Can_Irq.c
 **
 ** This generated file implements the interrupt service routines.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL40-DRV
 **
 ** (c) 2014-2017, Cypress Semiconductor Corporation. All rights reserved.
 **
 ** Warranty and Disclaimer
 **
 ** This software product is property of Cypress Semiconductor Corporation or
 ** its subsidiaries.
 ** Any use and/or distribution rights for this software product are provided
 ** only under the Cypress Software License Agreement.
 ** Any use and/or distribution of this software product not in accordance with
 ** the terms of the Cypress Software License Agreement are unauthorized and
 ** shall constitute an infringement of Cypress intellectual property rights.
 */

/*==================[inclusions]============================================*/

#include <Can_Cfg.h>
#include <Can.h>

/*==================[macros]================================================*/

/** Pointer to the IRC IRQ hold clear register.
    
    The macro can be overridden by the integrator via command line parameter.
    Doing so is at own risk! */
#ifndef CAN_IRC0IRQHC
  #define CAN_IRC0IRQHC (*((volatile uint32*)0xB0400C48uL))
#else
  /* Deviation from MISRA-C:2004 Rule 19.16:
     Unrecognized preprocessing directive has been ignored because of conditional inclusion directives.
     Justification: The preprocessing directive is a warning that indicates a special build 
     configuration which is not suitable for production software. */
  /* PRQA S 3115 1 */
  #warning CAN_IRC0IRQHC is overridden by the environment. This is not intended for production software!
#endif

/*==================[type definitions]======================================*/

/*==================[internal function declarations]========================*/

/*==================[internal constants]====================================*/

/*==================[internal data]=========================================*/

/*==================[external function definitions]=========================*/

#define CAN_START_SEC_CODE
/* MISRA-C:2004 Rule 19.1 deviation: MemMap.h must be included in-line. */ /* PRQA S 5087 1 */
#include "MemMap.h"

/** \brief Can_Interrupt_CAN1_Cat1
 **
 ** Category 1 interrupt service handler for controller CAN1.
 **
 */
ISR_NATIVE(Can_Interrupt_CAN1_Cat1)
{
  Can_InterruptHandler(CanConf_CanController_CanController_0);
  
  /* Reset interrupt controller hold bit. */
  /* Deviation of MISRA-C:2004 Rules 3.1, 11.3; REFERENCE - ISO:C90-6.3.4 Cast Operators - Semantics:
     Cast between a pointer to volatile object and an integral type.
     Justification: The hardware registers have absolute addresses, the cast cannot be avoided. */
  /* PRQA S 0303 1 */
  CAN_IRC0IRQHC = 57u;
}

/** \brief Can_Interrupt_CAN1_Cat2
 **
 ** Category 2 interrupt service handler for controller CAN1.
 **
 */
ISR(Can_Interrupt_CAN1_Cat2)
{
  Can_InterruptHandler(CanConf_CanController_CanController_0);
}

/** \brief Can_Interrupt_CAN6_Cat1
 **
 ** Category 1 interrupt service handler for controller CAN6.
 **
 */
ISR_NATIVE(Can_Interrupt_CAN6_Cat1)
{
  Can_InterruptHandler(CanConf_CanController_CanController_1);
  
  /* Reset interrupt controller hold bit. */
  /* Deviation of MISRA-C:2004 Rules 3.1, 11.3; REFERENCE - ISO:C90-6.3.4 Cast Operators - Semantics:
     Cast between a pointer to volatile object and an integral type.
     Justification: The hardware registers have absolute addresses, the cast cannot be avoided. */
  /* PRQA S 0303 1 */
  CAN_IRC0IRQHC = 49u;
}

/** \brief Can_Interrupt_CAN6_Cat2
 **
 ** Category 2 interrupt service handler for controller CAN6.
 **
 */
ISR(Can_Interrupt_CAN6_Cat2)
{
  Can_InterruptHandler(CanConf_CanController_CanController_1);
}

#define CAN_STOP_SEC_CODE
/* MISRA-C:2004 Rule 19.1 deviation: MemMap.h must be included in-line. */ /* PRQA S 5087 1 */
#include "MemMap.h"

/*==================[internal function definitions]=========================*/

/*==================[end of file]===========================================*/
