/** \brief AUTOSAR Port Port Driver
 **
 ** This file contains configuration data.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL40-DRV
 **
 ** (c) 2014-2017, Cypress Semiconductor Corporation. All rights reserved.
 **
 ** Warranty and Disclaimer
 **
 ** This software product is property of Cypress Semiconductor Corporation or
 ** its subsidiaries.
 ** Any use and/or distribution rights for this software product are provided
 ** only under the Cypress Software License Agreement.
 ** Any use and/or distribution of this software product not in accordance with
 ** the terms of the Cypress Software License Agreement are unauthorized and
 ** shall constitute an infringement of Cypress intellectual property rights.
*/
/*==================[inclusions]=============================================*/
#include <Port.h>              /* include architecture specific configuration part */

/*==================[macros]=================================================*/
/*==================[type definitions]=======================================*/
/*==================[external function declarations]=========================*/
/*==================[internal function declarations]=========================*/
/*==================[external constants]=====================================*/
/*==================[internal constants]=====================================*/
/*==================[external data]==========================================*/
#define PORT_START_SEC_CONST_UNSPECIFIED
#include <MemMap.h>

/* This data store PortPin Information. */
/* PRQA S 859 2 *//* Reason for disabling: For register setting of the 32bit width, 32 arguments are necessary. */
TS_STATIC_VAR CONST(Port_PinChannelConfigType,PORT_CONST)
  Port_PinConfig0_Channel_Config[PORT_PIN_NUMBER_OF_PORTS] = PORT_PIN_CFG0_CHANNEL_CONFIG;
/* PRQA S 859 2 *//* Reason for disabling: For register setting of the 32bit width, 32 arguments are necessary. */
TS_STATIC_VAR CONST(Port_PinChannelConfigType,PORT_CONST)
  Port_PinConfig1_Channel_Config[PORT_PIN_NUMBER_OF_PORTS] = PORT_PIN_CFG1_CHANNEL_CONFIG;


/* This data store ResourceInput Information for 16bit access. */
TS_STATIC_VAR CONST(Port_ResourceInput16bitConfigType,PORT_CONST)
  Port_16bitResourceInputConfig0_Channel_Config[PORT_NUMBER_OF_RESOURCEINPUTS_16BIT] = PORT_RESOURCEINPUTCONFIG0_CHANNEL_16BITCONFIG;
TS_STATIC_VAR CONST(Port_ResourceInput16bitConfigType,PORT_CONST)
  Port_16bitResourceInputConfig1_Channel_Config[PORT_NUMBER_OF_RESOURCEINPUTS_16BIT] = PORT_RESOURCEINPUTCONFIG1_CHANNEL_16BITCONFIG;



/* This data store Segment Output Information. */
/* PRQA S 859 2 *//* Reason for disabling: For register setting of the 32bit width, 32 arguments are necessary. */
TS_STATIC_VAR CONST(Port_SegerConfigType,PORT_CONST)
  Port_SegerConfig0_Config[PORT_NUMBER_OF_SEGEROUTPUTREG] = PORT_SEGER_CFG0_CONFIG;
/* PRQA S 859 2 *//* Reason for disabling: For register setting of the 32bit width, 32 arguments are necessary. */
TS_STATIC_VAR CONST(Port_SegerConfigType,PORT_CONST)
  Port_SegerConfig1_Config[PORT_NUMBER_OF_SEGEROUTPUTREG] = PORT_SEGER_CFG1_CONFIG;

/* This data store Common Output V Pin Information. */
/* PRQA S 859 2 *//* Reason for disabling: For register setting of the 32bit width, 32 arguments are necessary. */
TS_STATIC_VAR CONST(Port_ComverConfigType,PORT_CONST)
  Port_ComverConfig0_Config[PORT_NUMBER_OF_COMVEROUTPUTREG] = PORT_COMVER_CFG0_CONFIG;
/* PRQA S 859 2 *//* Reason for disabling: For register setting of the 32bit width, 32 arguments are necessary. */
TS_STATIC_VAR CONST(Port_ComverConfigType,PORT_CONST)
  Port_ComverConfig1_Config[PORT_NUMBER_OF_COMVEROUTPUTREG] = PORT_COMVER_CFG1_CONFIG;


/* This data store Post-Build's Port Configuration Information. */
CONST(Port_ConfigType,PORT_APPL_CONST) Port_PinConfigs[PORT_PIN_NUMBER_OF_CONFIGSETS] =
{
  {
    PORT_PIN_NUMBER_OF_PORTS,
    PORT_NUMBER_OF_ANALOGINPUTREG,
    PORT_NUMBER_OF_SEGEROUTPUTREG,
    PORT_NUMBER_OF_COMVEROUTPUTREG,
    PORT_NUMBER_OF_RESOURCEINPUTS_16BIT,
    PORT_NUMBER_OF_RESOURCEINPUTS_32BIT,
    &Port_PinConfig0_Channel_Config[0],
    &Port_16bitResourceInputConfig0_Channel_Config[0],
    NULL_PTR,
    NULL_PTR,
    &Port_SegerConfig0_Config[0],
    &Port_ComverConfig0_Config[0]
  },
  {
    PORT_PIN_NUMBER_OF_PORTS,
    PORT_NUMBER_OF_ANALOGINPUTREG,
    PORT_NUMBER_OF_SEGEROUTPUTREG,
    PORT_NUMBER_OF_COMVEROUTPUTREG,
    PORT_NUMBER_OF_RESOURCEINPUTS_16BIT,
    PORT_NUMBER_OF_RESOURCEINPUTS_32BIT,
    &Port_PinConfig1_Channel_Config[0],
    &Port_16bitResourceInputConfig1_Channel_Config[0],
    NULL_PTR,
    NULL_PTR,
    &Port_SegerConfig1_Config[0],
    &Port_ComverConfig1_Config[0]
  }
};


#define PORT_STOP_SEC_CONST_UNSPECIFIED
#include <MemMap.h> /* PRQA S 5087 *//* Reason for disabling: In AUTOSAR specification, it is a necessary process. */

/*==================[internal data]==========================================*/
/*==================[external function definitions]==========================*/
/*==================[internal function definitions]==========================*/

/*==================[end of file]============================================*/

