/** \brief Pwm_Irq.c
 **
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL40-DRV
 **
 ** (c) 2014-2017, Cypress Semiconductor Corporation. All rights reserved.
 **
 ** Warranty and Disclaimer
 **
 ** This software product is property of Cypress Semiconductor Corporation or
 ** its subsidiaries.
 ** Any use and/or distribution rights for this software product are provided
 ** only under the Cypress Software License Agreement.
 ** Any use and/or distribution of this software product not in accordance with
 ** the terms of the Cypress Software License Agreement are unauthorized and
 ** shall constitute an infringement of Cypress intellectual property rights.
 */

/*==================[inclusions]=============================================*/

#include <Pwm.h>
#include <Pwm_Internal.h>

/*==================[macros]=================================================*/

/** Pointer to the IRC IRQ hold clear register.
    
    The macro can be overridden by the integrator via command line parameter.
    Doing so is at own risk! */
#ifndef PWM_IRC0IRQHC
  #define PWM_IRC0IRQHC (*((volatile uint32*)0xB0400C48uL))
#else
  /* Deviation from MISRA-C:2004 Rule 19.16:
     Unrecognized preprocessing directive has been ignored because of conditional inclusion directives.
     Justification: The preprocessing directive is a warning that indicates a special build 
     configuration which is not suitable for production software. */
  /* PRQA S 3115 1 */
  #warning PWM_IRC0IRQHC is overridden by the environment. This is not intended for production software!
#endif

/*==================[type definitions]=======================================*/

/*==================[external function declarations]=========================*/

/*==================[internal function declarations]=========================*/

/*==================[external constants]=====================================*/

/*==================[internal constants]=====================================*/

/*==================[external data]==========================================*/

/*==================[internal data]==========================================*/

/*==================[external function definitions]==========================*/

#define PWM_START_SEC_CODE
/* MISRA-C:2004 Rule 19.1 deviation: MemMap.h must be included in-line. */ /* PRQA S 5087 1 */
#include <MemMap.h>

/** \brief Pwm_Isr_Channel_8_Cat1
 **
 ** Channel specific CAT1 interrupt handler which calls internal interrupt handler
 **
 ** The interrupt handler is associated to base timer 8 interrupt.
 */
ISR_NATIVE(Pwm_Isr_Channel_8_Cat1)
{
  Pwm_InterruptHandler(1u);
  Pwm_InterruptHandler(4u);
  Pwm_InterruptHandler(5u);
  /* Clear interrupt hold flag. */
  /* Deviation of MISRA-C:2004 Rules 3.1, 11.3; REFERENCE - ISO:C90-6.3.4 Cast Operators - Semantics:
     Cast between a pointer to volatile object and an integral type.
     Justification: Access to hardware register, which has an integral address. */
  /* PRQA S 0303 1 */
  PWM_IRC0IRQHC = 128u;
}

/** \brief Pwm_Isr_Channel_8_Cat2
 **
 ** Channel specific CAT2 interrupt handler which calls internal interrupt handler
 **
 ** The interrupt handler is associated to base timer 8 interrupt.
 */
ISR(Pwm_Isr_Channel_8_Cat2)
{
  Pwm_InterruptHandler(1u);
  Pwm_InterruptHandler(4u);
  Pwm_InterruptHandler(5u);
}

/** \brief Pwm_Isr_Channel_23_Cat1
 **
 ** Channel specific CAT1 interrupt handler which calls internal interrupt handler
 **
 ** The interrupt handler is associated to base timer 23 interrupt.
 */
ISR_NATIVE(Pwm_Isr_Channel_23_Cat1)
{
  Pwm_InterruptHandler(3u);
  Pwm_InterruptHandler(6u);
  Pwm_InterruptHandler(8u);
  /* Clear interrupt hold flag. */
  /* Deviation of MISRA-C:2004 Rules 3.1, 11.3; REFERENCE - ISO:C90-6.3.4 Cast Operators - Semantics:
     Cast between a pointer to volatile object and an integral type.
     Justification: Access to hardware register, which has an integral address. */
  /* PRQA S 0303 1 */
  PWM_IRC0IRQHC = 136u;
}

/** \brief Pwm_Isr_Channel_23_Cat2
 **
 ** Channel specific CAT2 interrupt handler which calls internal interrupt handler
 **
 ** The interrupt handler is associated to base timer 23 interrupt.
 */
ISR(Pwm_Isr_Channel_23_Cat2)
{
  Pwm_InterruptHandler(3u);
  Pwm_InterruptHandler(6u);
  Pwm_InterruptHandler(8u);
}

/** \brief Pwm_Isr_Channel_13_Cat1
 **
 ** Channel specific CAT1 interrupt handler which calls internal interrupt handler
 **
 ** The interrupt handler is associated to base timer 13 interrupt.
 */
ISR_NATIVE(Pwm_Isr_Channel_13_Cat1)
{
  Pwm_InterruptHandler(2u);
  /* Clear interrupt hold flag. */
  /* Deviation of MISRA-C:2004 Rules 3.1, 11.3; REFERENCE - ISO:C90-6.3.4 Cast Operators - Semantics:
     Cast between a pointer to volatile object and an integral type.
     Justification: Access to hardware register, which has an integral address. */
  /* PRQA S 0303 1 */
  PWM_IRC0IRQHC = 137u;
}

/** \brief Pwm_Isr_Channel_13_Cat2
 **
 ** Channel specific CAT2 interrupt handler which calls internal interrupt handler
 **
 ** The interrupt handler is associated to base timer 13 interrupt.
 */
ISR(Pwm_Isr_Channel_13_Cat2)
{
  Pwm_InterruptHandler(2u);
}

/** \brief Pwm_Isr_Channel_18_Cat1
 **
 ** Channel specific CAT1 interrupt handler which calls internal interrupt handler
 **
 ** The interrupt handler is associated to base timer 18 interrupt.
 */
ISR_NATIVE(Pwm_Isr_Channel_18_Cat1)
{
  Pwm_InterruptHandler(0u);
  /* Clear interrupt hold flag. */
  /* Deviation of MISRA-C:2004 Rules 3.1, 11.3; REFERENCE - ISO:C90-6.3.4 Cast Operators - Semantics:
     Cast between a pointer to volatile object and an integral type.
     Justification: Access to hardware register, which has an integral address. */
  /* PRQA S 0303 1 */
  PWM_IRC0IRQHC = 142u;
}

/** \brief Pwm_Isr_Channel_18_Cat2
 **
 ** Channel specific CAT2 interrupt handler which calls internal interrupt handler
 **
 ** The interrupt handler is associated to base timer 18 interrupt.
 */
ISR(Pwm_Isr_Channel_18_Cat2)
{
  Pwm_InterruptHandler(0u);
}

/** \brief Pwm_Isr_Channel_19_Cat1
 **
 ** Channel specific CAT1 interrupt handler which calls internal interrupt handler
 **
 ** The interrupt handler is associated to base timer 19 interrupt.
 */
ISR_NATIVE(Pwm_Isr_Channel_19_Cat1)
{
  Pwm_InterruptHandler(7u);
  /* Clear interrupt hold flag. */
  /* Deviation of MISRA-C:2004 Rules 3.1, 11.3; REFERENCE - ISO:C90-6.3.4 Cast Operators - Semantics:
     Cast between a pointer to volatile object and an integral type.
     Justification: Access to hardware register, which has an integral address. */
  /* PRQA S 0303 1 */
  PWM_IRC0IRQHC = 143u;
}

/** \brief Pwm_Isr_Channel_19_Cat2
 **
 ** Channel specific CAT2 interrupt handler which calls internal interrupt handler
 **
 ** The interrupt handler is associated to base timer 19 interrupt.
 */
ISR(Pwm_Isr_Channel_19_Cat2)
{
  Pwm_InterruptHandler(7u);
}

#define PWM_STOP_SEC_CODE
/* MISRA-C:2004 Rule 19.1 deviation: MemMap.h must be included in-line. */ /* PRQA S 5087 1 */
#include <MemMap.h>

/*==================[internal function definitions]==========================*/

/*==================[end of file]============================================*/
