
/** \brief AUTOSAR SPI Driver
 **
 ** This file contains implementation of the ISR functions.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL40-DRV
 **
 ** (c) 2016-2017, Cypress Semiconductor Corporation. All rights reserved.
 **
 ** Warranty and Disclaimer
 **
 ** This software product is property of Cypress Semiconductor Corporation or
 ** its subsidiaries.
 ** Any use and/or distribution rights for this software product are provided
 ** only under the Cypress Software License Agreement.
 ** Any use and/or distribution of this software product not in accordance with
 ** the terms of the Cypress Software License Agreement are unauthorized and
 ** shall constitute an infringement of Cypress intellectual property rights.
 */

/*==================[inclusions]============================================*/

/* This include was moved before IF-statement, because of empty file in case of SpiLevelDelivered equals 0! */
#include <Spi_Internal.h>         /* Module private API */


#include <Spi.h>
#include <Spi_Common.h>
#include <Spi_Hw.h>
#include <Spi_Cfg.h>
#include <Spi_Cfg_Der.h>

/*==================[macros]================================================*/

/** Base address of IRC IRQ Hold Clear hardware instance.
    The macro can be overridden by the integrator via command line parameter.
    Doing so is at own risk! */
#ifndef SPI_IRC0IRQHC_BASE_ADDRESS
/** Base-Address of hold clear bit of interrupt control unit. */
  #define SPI_IRC0IRQHC_BASE_ADDRESS  (volatile uint32*)0xB0400C48U
#else
  /* Deviation from MISRA-C:2004 Rule 19.16:
     Unrecognized preprocessing directive has been ignored because of conditional inclusion directives.
     Justification: The preprocessing directive is a warning that indicates a special build 
     configuration which is not suitable for production software. */
  /* PRQA S 3115 1 */
  #warning SPI_IRC0IRQHC_BASE_ADDRESS is overridden by the environment. This is not intended for production software!
#endif

/*==================[type definitions]======================================*/

/*==================[external function declarations]========================*/

/*==================[internal function declarations]========================*/
#define SPI_START_SEC_CODE
/* MISRA-C:2004 Rule 19.1 deviation: MemMap.h must be included in-line. */ /* PRQA S 5087 1 */
#include <MemMap.h>





#define SPI_STOP_SEC_CODE
/* MISRA-C:2004 Rule 19.1 deviation: MemMap.h must be included in-line. */ /* PRQA S 5087 1 */
#include <MemMap.h>

/*==================[external constants]====================================*/

/*==================[internal constants]====================================*/

/*==================[external data]=========================================*/

/*==================[internal data]=========================================*/

/*==================[external function definitions]=========================*/


#define SPI_START_SEC_CODE
/* MISRA-C:2004 Rule 19.1 deviation: MemMap.h must be included in-line. */ /* PRQA S 5087 1 */
#include <MemMap.h>




#define SPI_STOP_SEC_CODE
/* MISRA-C:2004 Rule 19.1 deviation: MemMap.h must be included in-line. */ /* PRQA S 5087 1 */
#include <MemMap.h>

/*==================[internal function definitions]=========================*/

#define SPI_START_SEC_CODE
/* MISRA-C:2004 Rule 19.1 deviation: MemMap.h must be included in-line. */ /* PRQA S 5087 1 */
#include <MemMap.h>



#define SPI_STOP_SEC_CODE
/* MISRA-C:2004 Rule 19.1 deviation: MemMap.h must be included in-line. */ /* PRQA S 5087 1 */
#include <MemMap.h>



/*==================[end of file]===========================================*/
