
/** \brief AUTOSAR SPI Driver
 **
 ** This file contains implementation of the main function handling.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL40-DRV
 **
 ** (c) 2016-2017, Cypress Semiconductor Corporation. All rights reserved.
 **
 ** Warranty and Disclaimer
 **
 ** This software product is property of Cypress Semiconductor Corporation or
 ** its subsidiaries.
 ** Any use and/or distribution rights for this software product are provided
 ** only under the Cypress Software License Agreement.
 ** Any use and/or distribution of this software product not in accordance with
 ** the terms of the Cypress Software License Agreement are unauthorized and
 ** shall constitute an infringement of Cypress intellectual property rights.
 */

/*==================[inclusions]============================================*/

#include <Std_Types.h>              /* AUTOSAR standard types */
#include <Spi.h>
#include <Spi_Hw.h>
#include <Spi_Internal.h>
#include <Spi_Job.h>
#include <Spi_Common.h>
#include <Spi_Common_Der.h>
#include <Spi_Cfg_Der.h>

/*==================[macros]================================================*/

/*==================[type definitions]======================================*/

/*==================[external function declarations]========================*/

/*==================[internal function declarations]========================*/

/*==================[external constants]====================================*/

/*==================[internal constants]====================================*/

/*==================[external data]=========================================*/

/*==================[internal data]=========================================*/

/*==================[external function definitions]=========================*/


#define SPI_START_SEC_CODE
/* MISRA-C:2004 Rule 19.1 deviation: MemMap.h must be included in-line. */ /* PRQA S 5087 1 */
#include <MemMap.h>

/** \brief Spi_MainFunction_Handling
 **
 ** Scheduled function that polls the SPI interrupt flags for advancing the transmission state machine.
 ** Only available if SPI_LEVEL_DELIVERED is 2.
 ** The function is only called if the transmission mode is set to SPI_POLLING_MODE using Spi_SetAsyncMode().
 **
 */
FUNC(void, SPI_CODE) Spi_MainFunction_Handling(void)
{
}

#define SPI_STOP_SEC_CODE
/* MISRA-C:2004 Rule 19.1 deviation: MemMap.h must be included in-line. */ /* PRQA S 5087 1 */
#include <MemMap.h>


/*==================[end of file]===========================================*/
